#nullable enable // autogenerated

using System.Collections.Generic;

namespace MVZ2Logic.Options
{
    public abstract class OptionDropdownDefinition : OptionWidgetDefinition
    {
        public OptionDropdownDefinition(string nsp, string name) : base(nsp, name)
        {
        }
        public override OptionWidgetType GetItemType()
        {
            return OptionWidgetType.Dropdown;
        }
        public abstract void FillItems(IOptionContext context, List<string> items);
        public abstract int GetValue(IOptionContext context);
        public abstract void OnValueChanged(IOptionContext context, int index);
    }
}
