#nullable enable // autogenerated

using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Level;

namespace MVZ2.GameContent.Stages
{
    public abstract class HeavyWeaponStageBase : StageDefinition
    {
        public HeavyWeaponStageBase(string nsp, string name) : base(nsp, name)
        {
            AddBehaviour(new WaveStageBehaviour(this));
            AddBehaviour(new FinalWaveClearBehaviour(this));
            AddBehaviour(new GemStageBehaviour(this));
            AddBehaviour(new RedstoneDropStageBehaviour(this));
            AddBehaviour(new HeavyWeaponStageBehaviour(this));
            AddBehaviour(new SpeedUpStageBehaviour(this, 1.5f, 2f));
        }
        public override void OnStart(LevelEngine level)
        {
            base.OnStart(level);
            var blueprints = GetBlueprintsID();
            level.SetSeedSlotCount(blueprints.Length);
            level.FillSeedPacks(blueprints);
        }
        protected abstract NamespaceID[] GetBlueprintsID();
    }
}
