#nullable enable // autogenerated

using System.Collections.Generic;

using MVZ2.GameContent.Buffs;

using MVZ2Logic.Artifacts;
using MVZ2Logic.Definitions;

using PVZEngine.Auras;
using PVZEngine.Buffs;

namespace MVZ2.GameContent.Artifacts
{
    [AutoArtifactDefinition(VanillaArtifactNames.LightBlock)]
    public class LightBlock : ArtifactDefinition
    {
        public LightBlock(string nsp, string name) : base(nsp, name)
        {
            AddAura(new DarkAura());
        }
        public override void PostUpdate(Artifact artifact)
        {
            base.PostUpdate(artifact);
            artifact.SetGlowing(true);
        }
        public class DarkAura : AuraEffectDefinition
        {
            public DarkAura() : base(VanillaBuffID.Level.DarkMatterDark)
            {
            }

            public override void GetAuraTargets(AuraEffect auraEffect, List<IBuffTarget> results)
            {
                results.Add(auraEffect.Source.GetLevel());
            }
        }

    }
}
