#nullable enable // autogenerated

using System;
using NCalc.Handlers;
using PVZEngine;
using PVZEngine.Base;

namespace MVZ2.Metas
{
    public static class AlmanacVariableFunctions
    {
        public static void EvaluateFunctions(AlmanacVariableContext context, string name, FunctionArgs args)
        {
            switch (name)
            {
                case "global":
                    args.Result = global(context, args);
                    break;
                case "local":
                    args.Result = local(context, args);
                    break;
                case "property":
                    args.Result = property(context, args);
                    break;
                case "toBoolean":
                    args.Result = toBoolean(context, args);
                    break;
                case "toShort":
                    args.Result = toShort(context, args);
                    break;
                case "toInt":
                    args.Result = toInt(context, args);
                    break;
                case "toLong":
                    args.Result = toLong(context, args);
                    break;
                case "toFloat":
                    args.Result = toFloat(context, args);
                    break;
                case "toDouble":
                    args.Result = toDouble(context, args);
                    break;
                case "toID":
                    args.Result = toID(context, args);
                    break;
            }
        }
        public static object? global(AlmanacVariableContext context, FunctionArgs args)
        {
            if (context == null)
                throw new Exception("No AlmanacVariableContext provided.");
            if (args.Parameters.Length == 1 && args.Parameters[0].Evaluate() is string idStr)
            {
                var id = NamespaceID.Parse(idStr, context.main.BuiltinNamespace);
                var variable = context.main.ResourceManager.GetAlmanacGlobalVariable(id);
                if (variable == null)
                    throw new Exception($"Cannot find global almanac variable {idStr}");


                if (!context.globalCallStack.Add(id))
                    throw new Exception($"Cyclic dependency detected: {idStr}");
                try
                {
                    return variable.GetVariableValue(context);
                }
                finally
                {
                    context.globalCallStack.Remove(id);
                }
            }
            throw new Exception("Invalid global() usage");
        }
        public static object? local(AlmanacVariableContext context, FunctionArgs args)
        {
            if (context == null)
                throw new Exception("No AlmanacVariableContext provided.");
            if (args.Parameters.Length == 1 && args.Parameters[0].Evaluate() is string idStr)
            {
                var variable = context.currentAlmanacEntry.GetLocalVariable(idStr);
                if (variable == null)
                    throw new Exception($"Cannot find local almanac variable {idStr} in entry {context.currentAlmanacEntry.name}");


                if (!context.localCallStack.Add(idStr))
                    throw new Exception($"Cyclic dependency detected: {idStr}");
                try
                {
                    return variable.GetVariableValue(context);
                }
                finally
                {
                    context.localCallStack.Remove(idStr);
                }
            }
            throw new Exception("Invalid local() usage");
        }
        public static object? property(AlmanacVariableContext context, FunctionArgs args)
        {
            if (context == null)
                throw new Exception("No AlmanacVariableContext provided.");
            var arg0 = args.Parameters[0].Evaluate();
            string? key = null;
            if (arg0 != null)
            {
                key = arg0.ToString();
                var propertyKey = PropertyMapper.ConvertFromName(key);
                if (propertyKey.IsValid())
                {

                    var definitionId = context.currentDefinitionID;
                    var definitionType = context.currentDefinitionType;

                    if (args.Parameters.Length >= 2)
                    {
                        var arg1 = args.Parameters[1].Evaluate();
                        if (arg1 is NamespaceID nid)
                            definitionId = nid;
                        else if (arg1 != null)
                            definitionId = NamespaceID.Parse(arg1.ToString(), context.main.BuiltinNamespace);
                        else
                            definitionId = null;
                    }
                    if (args.Parameters.Length >= 3)
                    {
                        var arg2 = args.Parameters[2].Evaluate();
                        if (arg2 != null)
                            definitionType = arg2.ToString();
                        else
                            definitionType = string.Empty;
                    }
                    var definition = context.main.Game.GetDefinition<Definition>(definitionType, definitionId);
                    if (definition == null)
                        throw new Exception($"Cannot find definition {definitionId} of type {definitionType} in variable of almanac entry {context.currentAlmanacEntry.name}.");

                    return definition.GetPropertyObject(propertyKey);
                }
            }
            throw new Exception($"Cannot find property of key {key} in variable of almanac entry {context.currentAlmanacEntry.name}.");
        }
        public static bool toBoolean(AlmanacVariableContext context, FunctionArgs args)
        {
            return Convert.ToBoolean(args.Parameters[0].Evaluate());
        }
        public static short toShort(AlmanacVariableContext context, FunctionArgs args)
        {
            return Convert.ToInt16(args.Parameters[0].Evaluate());
        }
        public static int toInt(AlmanacVariableContext context, FunctionArgs args)
        {
            return Convert.ToInt32(args.Parameters[0].Evaluate());
        }
        public static long toLong(AlmanacVariableContext context, FunctionArgs args)
        {
            return Convert.ToInt64(args.Parameters[0].Evaluate());
        }
        public static float toFloat(AlmanacVariableContext context, FunctionArgs args)
        {
            return Convert.ToSingle(args.Parameters[0].Evaluate());
        }
        public static double toDouble(AlmanacVariableContext context, FunctionArgs args)
        {
            return Convert.ToDouble(args.Parameters[0].Evaluate());
        }
        public static NamespaceID? toID(AlmanacVariableContext context, FunctionArgs args)
        {
            var arg0 = args.Parameters[0].Evaluate();
            if (arg0 is NamespaceID id)
                return id;
            if (arg0 == null)
                return null;
            return NamespaceID.Parse(arg0.ToString(), context.main.BuiltinNamespace);
        }
    }
}
