#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;

using PVZEngine.Buffs;
using PVZEngine.Definitions;

namespace MVZ2.GameContent.Buffs.Entities
{
    [AutoBuffDefinition(VanillaBuffNames.Entity.clearGridOnLand)]
    public class ClearGridOnLandBuff : BuffDefinition
    {
        public ClearGridOnLandBuff(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var entity = buff.GetEntity();
            if (entity == null)
                return;
            if (entity.IsOnGround)
            {
                entity.DestroyConflictGridEntities();
                buff.Remove();
            }
        }
    }
}
