#nullable enable // autogenerated

using System;
using PVZEngine;
using PVZEngine.Base;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace MVZ2.UI.Map
{
    public class MapElementButton : Selectable, IPointerClickHandler
    {
        void IPointerClickHandler.OnPointerClick(PointerEventData eventData)
        {
            if (!IsInteractable())
                return;
            // Not left mouse nor first touch.
            if (eventData.pointerId != -1 && eventData.pointerId != 0)
                return;
            OnClick?.Invoke(this);
        }
        public event Action<MapElementButton>? OnClick;
    }
}
