#nullable enable // autogenerated

using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Entities;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.mummy)]
    public class Mummy : AIEntityBehaviour, IDeathEffectsBehaviour
    {
        public Mummy(string nsp, string name) : base(nsp, name)
        {
        }
        public void DeathEffects(Entity entity, DeathInfo info)
        {
            var param = entity.GetSpawnParams();
            param.SetProperty(EngineEntityProps.SCALE, entity.GetScale());
            var gas = entity.Spawn(VanillaEffectID.mummyGas, entity.Position, param);
            entity.PlaySound(VanillaSoundID.poisonCast);

        }
    }
}
