#nullable enable // autogenerated

using System;
using UnityEngine;
using UnityEngine.UI;

namespace MVZ2.Almanacs
{
    public class AlmanacEntry : MonoBehaviour
    {
        public void UpdateEntry(AlmanacEntryViewData viewData)
        {
            rootObject.SetActive(!viewData.empty);
            var sprite = viewData.sprite;
            iconRoot.localPosition = (Vector3)viewData.offset;
            icon.sprite = sprite;
            icon.enabled = sprite;
            if (sprite.Exists())
            {
                ratioFitter.aspectRatio = sprite.rect.width / sprite.rect.height;
            }
            else
            {
                ratioFitter.aspectRatio = 1;
            }
        }
        private void Awake()
        {
            button.onClick.AddListener(() => OnClick?.Invoke(this));
        }
        public event Action<AlmanacEntry>? OnClick;
        [SerializeField]
        private GameObject rootObject = null!;
        [SerializeField]
        private Button button = null!;
        [SerializeField]
        private RectTransform iconRoot = null!;
        [SerializeField]
        private Image icon = null!;
        [SerializeField]
        private AspectRatioFitter ratioFitter = null!;
    }
    public struct AlmanacEntryViewData
    {
        public bool empty;
        public Sprite? sprite;
        public Vector2 offset;
        public static readonly AlmanacEntryViewData Empty = new AlmanacEntryViewData { empty = true };
    }
}
