#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using PVZEngine.Collisions;
using PVZEngine.Collisions.Level;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Definitions;
using Tools.Geometrical;
using UnityEngine;

namespace MVZ2.Vanilla.Detections
{
    public static class Detection
    {
        public static bool Intersects(this Hitbox self, Hitbox other)
        {
            Bounds selfBounds = self.GetBounds();
            Bounds otherBounds = other.GetBounds();
            return selfBounds.IntersectsOptimized(otherBounds);
        }
        public static bool Intersects(Vector3 center1, Vector3 size1, Vector3 center2, Vector3 size2)
        {
            var bounds1 = new Bounds(center1, size1);
            var bounds2 = new Bounds(center2, size2);
            return bounds1.IntersectsOptimized(bounds2);
        }
        public static bool CanDetect(Entity entity)
        {
            return !entity.IsInvisible();
        }

        #region Xǰ��
        public static bool IsInTheFrontOf(this float x1, float x2, bool x2FaceLeft)
        {
            if (x2FaceLeft)
            {
                return x1 < x2;
            }
            else
            {
                return x1 > x2;
            }
        }
        public static bool IsInTheFrontOf(this Entity entity, float x)
        {
            if (entity.IsFacingLeft())
            {
                return entity.Position.x < x;
            }
            else
            {
                return entity.Position.x > x;
            }
        }
        public static bool IsInTheFrontOfRange(this Entity entity, float x, float length)
        {
            if (entity.IsFacingLeft())
            {
                return entity.Position.x < x && entity.Position.x > x + length;
            }
            else
            {
                return entity.Position.x > x && entity.Position.x < x + length;
            }
        }
        #endregion

        #region ʵ��ǰ��
        public static bool IsAheadOf(this Entity entity, Entity target, float minDistance = 0)
        {
            if (target.IsFacingLeft())
            {
                return entity.Position.x < target.Position.x - minDistance;
            }
            else
            {
                return entity.Position.x > target.Position.x + minDistance;
            }
        }
        public static bool IsAheadOfRange(this Entity entity, Entity target, float minDistance, float maxDistance)
        {
            if (target.IsFacingLeft())
            {
                return entity.Position.x < target.Position.x - minDistance && entity.Position.x > target.Position.x - maxDistance;
            }
            else
            {
                return entity.Position.x > target.Position.x + minDistance && entity.Position.x < target.Position.x + maxDistance;
            }
        }
        #endregion

        #region ��ǰ��
        public static bool IsAheadOfColumn(this Entity entity, int column)
        {
            if (entity.IsFacingLeft())
            {
                return entity.GetColumn() < column;
            }
            else
            {
                return entity.GetColumn() > column;
            }
        }
        public static bool IsAheadOfOrAtColumn(this Entity entity, int column)
        {
            return !entity.IsBehindOfColumn(column);
        }
        #endregion

        #region X��
        public static bool IsInTheRearOf(this float x1, float x2, bool x2FaceLeft)
        {
            if (x2FaceLeft)
            {
                return x1 > x2;
            }
            else
            {
                return x1 < x2;
            }
        }
        public static bool IsInTheRearOf(this Entity entity, float x)
        {
            if (entity.IsFacingLeft())
            {
                return entity.Position.x > x;
            }
            else
            {
                return entity.Position.x < x;
            }
        }
        public static bool IsInTheRearOfRange(this Entity entity, float x, float length)
        {
            if (entity.IsFacingLeft())
            {
                return entity.Position.x > x && entity.Position.x < x + length;
            }
            else
            {
                return entity.Position.x < x && entity.Position.x > x + length;
            }
        }
        #endregion

        #region ʵ���
        public static bool IsBehindOf(this Entity entity, Entity target, float minDistance = 0)
        {
            if (target.IsFacingLeft())
            {
                return entity.Position.x > target.Position.x - minDistance;
            }
            else
            {
                return entity.Position.x < target.Position.x + minDistance;
            }
        }
        public static bool IsBehindOfRange(this Entity entity, Entity target, float minDistance, float maxDistance)
        {
            if (target.IsFacingLeft())
            {
                return entity.Position.x > target.Position.x - minDistance && entity.Position.x < target.Position.x - maxDistance;
            }
            else
            {
                return entity.Position.x < target.Position.x + minDistance && entity.Position.x > target.Position.x + maxDistance;
            }
        }
        #endregion

        #region �к�
        public static bool IsBehindOfColumn(this Entity entity, int column)
        {
            if (entity.IsFacingLeft())
            {
                return entity.GetColumn() > column;
            }
            else
            {
                return entity.GetColumn() < column;
            }
        }
        public static bool IsBehindOfOrAtColumn(this Entity entity, int column)
        {
            return !entity.IsAheadOfColumn(column);
        }
        #endregion

        #region X related
        public static bool IsXCoincide(float x1, float xLength1, float x2, float xLength2)
        {
            float extent1 = xLength1 / 2;
            float extent2 = xLength2 / 2;
            return Geometry.DoRangesIntersect(x1 - extent1, x1 + extent1, x2 - extent2, x2 + extent2);
        }
        #endregion

        #region Y related
        public static bool CoincidesYDown(this Bounds bounds, float y)
        {
            return bounds.min.y < y;
        }
        public static bool CoincidesYUp(this Bounds bounds, float y)
        {
            return bounds.max.y > y;
        }
        public static bool IsYCoincide(float y1, float yLength1, float y2, float yLength2)
        {
            return Geometry.DoRangesIntersect(y1, y1 + yLength1, y2, y2 + yLength2);
        }
        #endregion

        #region Z related
        public static bool IsInSameRow(Entity self, Entity other)
        {
            return self.GetLane() == other.GetLane();
        }
        public static bool IsZCoincide(float z1, float zLength1, float z2, float zLength2)
        {
            float extent1 = zLength1 / 2;
            float extent2 = zLength2 / 2;
            return Geometry.DoRangesIntersect(z1 - extent1, z1 + extent1, z2 - extent2, z2 + extent2);
        }
        #endregion

        public static void OverlapGridGroundNonAlloc(this LevelEngine level, int column, int lane, OverlapParams param, List<IEntityCollider> results)
        {
            var sizeX = level.GetGridWidth();
            var sizeY = 200;
            var sizeZ = level.GetGridHeight();
            var minX = level.GetColumnX(column);
            var minZ = level.GetEntityLaneZ(lane) - sizeZ * 0.5f;
            var centerX = minX + sizeX * 0.5f;
            var centerZ = minZ + sizeZ * 0.5f;
            var centerY = level.GetGroundY(centerX, centerZ) - sizeY * 0.5f;
            var center = new Vector3(centerX, centerY, centerZ);
            var size = new Vector3(sizeX, sizeY, sizeZ);
            level.OverlapBoxNonAlloc(center, size, param, results);
        }
    }
}