#nullable enable // autogenerated

using MVZ2Logic;
using UnityEngine;

namespace MVZ2.Models
{
    [RequireComponent(typeof(SpriteRenderer))]
    public class ModelPropertySpriteSetter : ModelComponent
    {
        public override void UpdateFrame(float deltaTime)
        {
            var reference = GetSpriteReference();
            if (reference != beforeReference || (Application.isEditor && !Application.isPlaying))
            {
                if (Main)
                {
                    beforeReference = reference;
                    var sprite = Main.GetFinalSprite(reference);
                    Renderer.sprite = sprite;
                }
            }
        }
        public SpriteReference? GetSpriteReference()
        {
            return Model.GetProperty<SpriteReference>(propertyName);
        }
        private SpriteRenderer Renderer
        {
            get
            {
                if (!sprRenderer.Exists())
                {
                    sprRenderer = GetComponent<SpriteRenderer>();
                }
                return sprRenderer;
            }
        }
        private SpriteRenderer? sprRenderer;
        private SpriteReference? beforeReference;
        public string propertyName;
    }
}