#nullable enable // autogenerated  

using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Contraptions;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.stoneDropper)]
    public class StoneDropper : DispenserFamily
    {
        public StoneDropper(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            InitShootTimer(entity);
            SetTriggerCooldownTimer(entity, new FrameTimer(0)); // 初始化为0，放下立即可触发  
        }

        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);

            // 更新触发冷却计时器  
            var cooldownTimer = GetTriggerCooldownTimer(entity);
            if (cooldownTimer != null)
            {
                cooldownTimer.Run(entity.GetAttackSpeed());
            }
            // 更新冷却状态属性  
            var cooldownTimer0 = GetTriggerCooldownTimer(entity);
            bool isOnCooldown = cooldownTimer0 != null && !cooldownTimer0.Expired;
            entity.SetModelProperty("OnCooldown", isOnCooldown);

            if (!entity.IsEvoked())
            {
                ShootTick(entity);
                return;
            }
        }

        public override bool CanTrigger(Entity entity)
        {
            // 检查基础触发条件  
            if (!base.CanTrigger(entity))
                return false;

            // 检查是否在冷却中  
            var cooldownTimer = GetTriggerCooldownTimer(entity);
            if (cooldownTimer != null && !cooldownTimer.Expired)
                return false;

            return true;
        }

        public override Entity? Shoot(Entity entity)
        {
            if (entity.RNG.Next(4) == 0)
            {
                var param = entity.GetShootParams();
                param.projectileID = VanillaProjectileID.boulder;
                param.damage = entity.GetDamage() * 4;
                return entity.ShootProjectile(param);
            }
            return base.Shoot(entity);
        }

        protected override void OnTrigger(Entity entity)
        {
            base.OnTrigger(entity);

            // 触发后立刻发射一发巨石    
            var param = entity.GetShootParams();
            param.projectileID = VanillaProjectileID.boulder;
            param.damage = entity.GetDamage() * 4;

            // 根据朝向调整速度方向  
            var velocity = entity.GetShotVelocity();
            if (entity.IsFacingLeft())
            {
                velocity.x *= -1;
            }
            param.velocity = velocity;

            entity.ShootProjectile(param);
            entity.PlaySound(VanillaSoundID.launch);

            // 重置冷却计时器    
            var cooldownTimer = GetTriggerCooldownTimer(entity);
            if (cooldownTimer != null)
            {
                cooldownTimer.ResetTime(TRIGGER_COOLDOWN);
            }
        }

        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            var rng = entity.RNG;
            for (int i = 0; i < 30; i++)
            {
                var xspeed = entity.GetFacingX() * rng.Next(10f, 18f);
                var yspeed = rng.Next(30f);
                var zspeed = rng.Next(-1.5f, 1.5f);
                var param = entity.GetShootParams();
                param.projectileID = VanillaProjectileID.boulder;
                param.velocity = new Vector3(xspeed, yspeed, zspeed);
                entity.ShootProjectile(param);
            }
            entity.PlaySound(VanillaSoundID.launch);
        }

        private static readonly NamespaceID ID = VanillaContraptionID.stoneDropper;
        private static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_TRIGGER_COOLDOWN_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("TriggerCooldownTimer");

        private static FrameTimer? GetTriggerCooldownTimer(Entity entity) => entity.GetBehaviourField<FrameTimer>(ID, PROP_TRIGGER_COOLDOWN_TIMER);
        private static void SetTriggerCooldownTimer(Entity entity, FrameTimer timer) => entity.SetBehaviourField(ID, PROP_TRIGGER_COOLDOWN_TIMER, timer);

        public const int TRIGGER_COOLDOWN = 90;
    }
}