#nullable enable // autogenerated

using PVZEngine.Definitions;
using PVZEngine.Level;

namespace MVZ2.GameContent.Stages
{
    [AutoStageDefinition(VanillaStageNames.puzzleIZombieEndless)]
    public class PuzzleIZombieEndlessStage : StageDefinition
    {
        public PuzzleIZombieEndlessStage(string nsp, string name) : base(nsp, name)
        {
            AddBehaviour(new IZombieEndlessBehaviour(this));
        }
    }
}
