#nullable enable // autogenerated

using PVZEngine.Definitions;

namespace MVZ2.GameContent.Effects
{
    [AutoEntityBehaviourDefinition(VanillaEffectNames.goreParticles)]
    public class GoreParticles : EffectBehaviour
    {

        #region 公有方法
        public GoreParticles(string nsp, string name) : base(nsp, name)
        {
        }
        #endregion
    }
}