#nullable enable // autogenerated

using MVZ2Logic;
using MVZ2Logic.Definitions;
using MVZ2Logic.Notes;

namespace MVZ2.GameContent.Notes
{
    [AutoNoteDefinition(VanillaNoteNames.palace)]
    public class PalaceNote : NoteDefinition
    {
        public PalaceNote(string nsp, string name) : base(nsp, name)
        {
        }
        public override void OnBack(INote note)
        {
            base.OnBack(note);
            Global.Scene.GotoMapOrMainmenu();
        }
    }
}
