#nullable enable // autogenerated

using MVZ2.GameContent.Difficulties;
using PVZEngine.Buffs;
using PVZEngine.Level;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Level
{
    [BuffDefinition(VanillaBuffNames.Level.iZombieLunatic)]
    public class iZombieLunaticBuff : BuffDefinition
    {
        public iZombieLunaticBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new IntModifier(VanillaDifficultyLevelProps.IZ_FURNACE_REDSTONE_COUNT, IntegerOperator.Add, -2));
        }
    }
}
