#nullable enable // autogenerated

using System;
using System.Linq;
using MVZ2Logic.Games;
using PVZEngine;

namespace MVZ2Logic.Options
{
    public static class LogicOptionExt
    {
        #region 语言
        public static string GetLanguage(this IGlobalOptions options) => options.GetOptionString(LogicOptionItemID.language);
        public static void SetLanguage(this IGlobalOptions options, string language) => options.SetOptionString(LogicOptionItemID.language, language);
        public static bool IsLanguageInitialized(this IGlobalOptions options) => options.TryGetOptionString(LogicOptionItemID.language, out var lang) && !string.IsNullOrEmpty(lang);
        #endregion

        #region 难度
        public static NamespaceID GetDifficulty(this IGlobalOptions options) => options.GetOptionID(LogicOptionItemID.difficulty) ?? GetDefaultDifficulty();
        public static void SetDifficulty(this IGlobalOptions options, NamespaceID difficulty) => options.SetOptionID(LogicOptionItemID.difficulty, difficulty);
        public static void CycleDifficulty(this IGlobalOptions options)
        {
            var difficulties = Global.Game.GetAllDifficultyDefinitions().Select(d => d.GetID()).ToArray();
            var index = Array.IndexOf(difficulties, options.GetDifficulty());
            index++;
            index %= difficulties.Length;
            options.SetDifficulty(difficulties[index]);
        }
        private static NamespaceID GetDefaultDifficulty()
        {
            return new NamespaceID(Global.BuiltinNamespace, "normal");
        }
        #endregion

        #region 交换触发
        public static bool IsTriggerSwapped(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.swapTrigger);
        public static void SetSwapTrigger(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.swapTrigger, value);
        #endregion

        #region 全屏
        public static bool IsFullscreen(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.fullscreen);
        public static void SetFullscreen(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.fullscreen, value);
        #endregion

        #region HDR
        public static bool HDRLightingDisabled(this IGlobalOptions options) => !options.GetOptionBool(LogicOptionItemID.hdrLighting);
        public static void SetHDRLightingDisabled(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.hdrLighting, !value);
        #endregion

        #region 震动
        public static bool IsVibration(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.vibration);
        public static void SetVibration(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.fullscreen, value);
        #endregion

        #region 血与碎块
        public static bool HasBloodAndGore(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.bloodAndGore);
        public static void SetBloodAndGore(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.bloodAndGore, value);
        #endregion

        #region 焦点丢失暂停
        public static bool GetPauseOnFocusLost(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.pauseOnFocusLost);
        public static void SetPauseOnFocusLost(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.pauseOnFocusLost, value);
        #endregion

        #region 显示赞助者名称
        public static bool ShowSponsorNames(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.showSponsorNames);
        public static void SetShowSponsorNames(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.showSponsorNames, value);
        #endregion

        #region 跳过对话
        public static bool SkipAllTalks(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.skipTalks);
        public static void SetSkipAllTalks(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.skipTalks, value);
        #endregion

        #region 蓝图选择警告
        public static bool AreBlueprintChooseWarningsDisabled(this IGlobalOptions options) => !options.GetOptionBool(LogicOptionItemID.blueprintWarnings);
        public static void SetBlueprintChooseWarningsDisabled(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.skipTalks, !value);
        #endregion

        #region 命令方块模式
        public static int GetCommandBlockMode(this IGlobalOptions options) => options.GetOptionInt(LogicOptionItemID.commandBlockMode);
        public static void SetCommandBlockMode(this IGlobalOptions options, int value) => options.SetOptionInt(LogicOptionItemID.commandBlockMode, value);
        public static void CycleCommandBlockMode(this IGlobalOptions options)
        {
            var mode = options.GetCommandBlockMode();
            mode = (mode + 1) % CommandBlockModes.COUNT;
            options.SetCommandBlockMode(mode);
        }
        #endregion

        #region FPS显示
        public static int GetFPSMode(this IGlobalOptions options) => options.GetOptionInt(LogicOptionItemID.fpsMode);
        public static void SetFPSMode(this IGlobalOptions options, int value) => options.SetOptionInt(LogicOptionItemID.fpsMode, value);
        public static void CycleFPSMode(this IGlobalOptions options)
        {
            var mode = options.GetFPSMode();
            mode = (mode + 1) % FPSModes.COUNT;
            options.SetFPSMode(mode);
        }
        #endregion

        #region 热键显示
        public static bool ShowHotkeyIndicators(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.showHotkeys);
        public static void SetShowHotkeyIndicators(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.showHotkeys, value);
        #endregion

        #region 高度指示器
        public static bool IsHeightIndicatorEnabled(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.heightIndicator);
        public static void SetHeightIndicatorEnabled(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.heightIndicator, value);
        #endregion

        #region 血条
        public static bool IsHPBarEnabled(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.hpBarEnabled);
        public static void SetHPBarEnabled(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.hpBarEnabled, value);
        public static void SwitchHPBarEnabled(this IGlobalOptions options) => options.SetHPBarEnabled(!options.IsHPBarEnabled());


        public static bool IsHPBarAutoHide(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.hpBarAutoHide);
        public static void SetHPBarAutoHide(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.hpBarAutoHide, value);


        public static float GetHPBarHoverDisplayRange(this IGlobalOptions options) => options.GetOptionFloat(LogicOptionItemID.hpBarHoverDisplayRange);
        public static void SetHPBarHoverDisplayRange(this IGlobalOptions options, float value) => options.SetOptionFloat(LogicOptionItemID.hpBarHoverDisplayRange, value);

        public static int GetHPBarAmountMode(this IGlobalOptions options) => options.GetOptionInt(LogicOptionItemID.hpBarAmountMode);
        public static void SetHPBarAmountMode(this IGlobalOptions options, int value) => options.SetOptionInt(LogicOptionItemID.hpBarAmountMode, value);
        public static void CycleHPBarAmountMode(this IGlobalOptions options)
        {
            var mode = options.GetHPBarAmountMode();
            mode = (mode + 1) % HPBarAmountMode.COUNT;
            options.SetHPBarAmountMode(mode);
        }
        #endregion

        #region 音乐音量
        public static float GetMusicVolume(this IGlobalOptions options) => options.GetOptionFloat(LogicOptionItemID.musicVolume);
        public static void SetMusicVolume(this IGlobalOptions options, float value) => options.SetOptionFloat(LogicOptionItemID.musicVolume, value);
        #endregion

        #region 音效音量
        public static float GetSoundVolume(this IGlobalOptions options) => options.GetOptionFloat(LogicOptionItemID.soundVolume);
        public static void SetSoundVolume(this IGlobalOptions options, float value) => options.SetOptionFloat(LogicOptionItemID.soundVolume, value);
        #endregion

        #region 快进倍率
        public static float GetFastForwardMultiplier(this IGlobalOptions options) => options.GetOptionFloat(LogicOptionItemID.fastForwardMultiplier);
        public static void SetFastForwardMultiplier(this IGlobalOptions options, float value) => options.SetOptionFloat(LogicOptionItemID.fastForwardMultiplier, value);
        #endregion

        #region 粒子数量
        public static float GetParticleAmount(this IGlobalOptions options) => options.GetOptionFloat(LogicOptionItemID.particleAmount);
        public static void SetParticleAmount(this IGlobalOptions options, float value) => options.SetOptionFloat(LogicOptionItemID.particleAmount, value);
        #endregion

        #region 震动幅度
        public static float GetShakeAmount(this IGlobalOptions options) => options.GetOptionFloat(LogicOptionItemID.shakeAmount);
        public static void SetShakeAmount(this IGlobalOptions options, float value) => options.SetOptionFloat(LogicOptionItemID.shakeAmount, value);
        #endregion

        #region 动画频率
        public static float GetAnimationFrequency(this IGlobalOptions options) => options.GetOptionFloat(LogicOptionItemID.animationFrequency);
        public static void SetAnimationFrequency(this IGlobalOptions options, float value) => options.SetOptionFloat(LogicOptionItemID.animationFrequency, value);
        #endregion

        #region 垂直同步
        public static bool GetVSync(this IGlobalOptions options) => options.GetOptionBool(LogicOptionItemID.vSync);
        public static void SetVSync(this IGlobalOptions options, bool value) => options.SetOptionBool(LogicOptionItemID.vSync, value);
        #endregion

        #region 目标帧率
        public static int GetTargetFramerate(this IGlobalOptions options) => options.GetOptionInt(LogicOptionItemID.targetFramerate);
        public static void SetTargetFramerate(this IGlobalOptions options, int value) => options.SetOptionInt(LogicOptionItemID.targetFramerate, value);
        #endregion
    }
}
