#nullable enable // autogenerated

using MVZ2.GameContent.Seeds;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Definitions;
using PVZEngine.Level;

namespace MVZ2.GameContent.Stages
{
    [AutoStageDefinition(VanillaStageNames.PacZombie)]
    public partial class PacZombie : StageDefinition
    {
        public PacZombie(string nsp, string name) : base(nsp, name)
        {

            AddBehaviour(new WaveStageBehaviour(this));
            AddBehaviour(new FinalWaveClearBehaviour(this));
            AddBehaviour(new GemStageBehaviour(this));
            AddBehaviour(new PacZombieStageBehaviour(this));
            AddBehaviour(new RedstoneDropStageBehaviour(this));
            AddBehaviour(new SpeedUpStageBehaviour(this, 1.5f, 2f));
        }
        public override void OnStart(LevelEngine level)
        {
            base.OnStart(level);
            var blueprints = new NamespaceID[]
            {
                VanillaBlueprintID.heavyWeaponFlashbang,
                VanillaBlueprintID.HeavyWeaponSelfDestruct,
                VanillaBlueprintID.HeavyWeaponInvincible,
                VanillaBlueprintID.HeavyWeaponHeal,
                VanillaBlueprintID.HeavyWeaponRegen,
                VanillaBlueprintID.HeavyWeaponExtraLife,
                VanillaBlueprintID.HeavyWeaponAttackUp,
                VanillaBlueprintID.HeavyWeaponSpeedUp,
            };
            level.SetSeedSlotCount(blueprints.Length);
            level.FillSeedPacks(blueprints);
        }
    }
}
