#nullable enable // autogenerated

using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.crusherBall)]
    public class CrusherBall : EntityBehaviourDefinition
    {
        public CrusherBall(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.CollisionMaskHostile |= EntityCollisionHelper.MASK_CART;
        }

        public override void PostCollision(EntityCollision collision, int state)
        {
            base.PostCollision(collision, state);
            if (state == EntityCollisionHelper.STATE_EXIT)
                return;
            if (!collision.Collider.IsForMain())
                return;
            var other = collision.Other;
            var bale = collision.Entity;
            if (!bale.IsHostile(other))
                return;

            if (other.Type == EntityTypes.CART)
            {
                other.Die(bale);
                other.PlaySound(VanillaSoundID.smash);
            }
            else if (other.IsVulnerableEntity())
            {
                HellChariot.Crush(bale, collision.OtherCollider);
            }
        }
    }
}
