#nullable enable // autogenerated

using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Pickups;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Pickups
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.pickupCollectLockedChest)]
    public class CollectBehaviour_LockedChest : CollectBehaviour
    {
        public CollectBehaviour_LockedChest(string nsp, string name) : base(nsp, name)
        {
        }
        public override bool CanCollect(Entity pickup)
        {
            return true;
        }
        public override void PostCollect(Entity pickup)
        {
            base.PostCollect(pickup);
            pickup.Velocity = Vector3.zero;
            var level = pickup.Level;

            level.ResetHeldItem();
            level.StopMusic();
            level.PlaySoundIfNotNull(pickup.GetCollectSound());
            level.PlaySound(VanillaSoundID.winMusic);
            level.Spawn(VanillaEffectID.starParticles, pickup.Position, pickup);

            LockedChestPickup.GetOrInitStateTimer(pickup).ResetSeconds(LockedChestPickup.SECONDS_TO_START_TALK);
        }
    }
}