#nullable enable // autogenerated

using MVZ2.GameContent.Enemies;
using MVZ2Logic.Spawns;
using PVZEngine.Definitions;

namespace MVZ2.GameContent.Spawns
{
    [AutoSpawnDefinition(VanillaSpawnNames.undeadFlyingObject)]
    public class UFOSpawnDefinition : LogicSpawnDefinition
    {
        public UFOSpawnDefinition(string nsp, string name) : base(nsp, name)
        {
            var preview = new SpawnPreviewBehaviour();
            var inLevel = new UFOSpawnInLevelBehaviour();
            var endless = new SpawnEndlessBehaviour();
            SetBehaviours(inLevel, preview, endless);
        }
    }
}
