#nullable enable // autogenerated

using System;
using System.Linq;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using PVZEngine;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Spawns
{
    public class VanillaSpawnDefinition : SpawnDefinition
    {
        public VanillaSpawnDefinition(string nsp, string name) : base(nsp, name)
        {
        }
        public void SetBehaviours(ISpawnInLevelBehaviour inLevelBehaviour, ISpawnPreviewBehaviour previewBehaviour, ISpawnEndlessBehaviour endlessBehaviour)
        {
            this.inLevelBehaviour = inLevelBehaviour;
            this.previewBehaviour = previewBehaviour;
            this.endlessBehaviour = endlessBehaviour;
        }
        protected override ISpawnPreviewBehaviour GetPreviewBehaviour() => previewBehaviour;
        protected override ISpawnInLevelBehaviour GetInLevelBehaviour() => inLevelBehaviour;
        protected override ISpawnEndlessBehaviour GetEndlessBehaviour() => endlessBehaviour;
        private ISpawnInLevelBehaviour inLevelBehaviour = null!;
        private ISpawnPreviewBehaviour previewBehaviour = null!;
        private ISpawnEndlessBehaviour endlessBehaviour = null!;
    }
    public class SpawnInLevelBehaviour : ISpawnInLevelBehaviour
    {
        public SpawnInLevelBehaviour()
        {
        }

        public void PreSpawnAtWave(SpawnDefinition definition, LevelEngine level, int wave, ref float totalPoints)
        {
        }
        public int GetRandomSpawnLane(SpawnDefinition definition, LevelEngine level)
        {
            var allLanes = level.GetAllLanes();
            var resultLanes = allLanes;

            bool isStartWaves = level.CurrentFlag <= 0 && level.CurrentWave <= 3;
            if (isStartWaves || !definition.SpawnInWater())
            {
                var waterLanes = level.GetWaterLanes();
                resultLanes = resultLanes.Except(waterLanes);
            }
            if (isStartWaves || !definition.SpawnInAir())
            {
                var airLanes = level.GetAirLanes();
                resultLanes = resultLanes.Except(airLanes);
            }

            if (resultLanes.Count() <= 0)
            {
                resultLanes = allLanes;
            }
            return level.GetRandomEnemySpawnLane(resultLanes);
        }
        public bool CanSpawnInLevel(SpawnDefinition definition, LevelEngine level)
        {
            return definition.GetSpawnLevel() > 0;
        }
        public int GetWeight(SpawnDefinition definition, LevelEngine level)
        {
            var weight = definition.GetWeightBase();
            var decayStart = definition.GetWeightDecayStartFlag();
            var decayEnd = definition.GetWeightDecayEndFlag();
            var decay = definition.GetWeightDecayPerFlag();

            var decayFlags = Mathf.Clamp(level.CurrentFlag, decayStart, decayEnd) - decayStart;
            return weight - decay * decayFlags;
        }
    }
    public class SpawnPreviewBehaviour : ISpawnPreviewBehaviour
    {
        public SpawnPreviewBehaviour()
        {
        }
        public Entity? SpawnPreviewEntity(SpawnDefinition definition, LevelEngine level, Vector3 pos, SpawnParams param)
        {
            var entityId = definition.GetPreviewEntity();
            if (!NamespaceID.IsValid(entityId))
                return null;
            var entityVariant = definition.GetPreviewVariant();
            param.SetProperty(VanillaEntityProps.VARIANT, entityVariant);
            return level.Spawn(entityId, pos, null, param);
        }
        public NamespaceID[] GetCounterTags(SpawnDefinition definition, LevelEngine level)
        {
            var entityID = definition.GetPreviewEntity();
            if (!NamespaceID.IsValid(entityID))
                return Array.Empty<NamespaceID>();
            var entityDef = level.Content.GetEntityDefinition(entityID);
            return entityDef?.GetCounterTags() ?? Array.Empty<NamespaceID>();
        }
    }
    public class SpawnEndlessBehaviour : ISpawnEndlessBehaviour
    {
        public SpawnEndlessBehaviour()
        {
        }
        public bool CanAppearInEndless(SpawnDefinition definition, LevelEngine level)
        {
            if (definition.IsNoEndless() || definition.GetSpawnLevel() <= 0)
                return false;
            var excludedAreaTags = definition.GetExcludedAreaTags();
            var areaDef = level.AreaDefinition;
            if (areaDef.GetAreaTags().Any(t => excludedAreaTags.Contains(t)))
                return false;
            return true;
        }
    }
}
