#nullable enable // autogenerated

using MVZ2Logic.Entities;
using PVZEngine.Entities;

namespace MVZ2.Vanilla.Entities
{
    public abstract class ContraptionEvokeBehaviour : EntityBehaviourDefinition, IContraptionEvokeBehaviour
    {
        public ContraptionEvokeBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        public virtual bool CanEvoke(Entity entity)
        {
            return !entity.IsEvoked() && !entity.IsAIFrozen() && !entity.NoEvoke();
        }
        public virtual void Evoke(Entity entity)
        {
        }
    }
}