#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Obstacles;
using MVZ2.Vanilla.Grids;
using MVZ2Logic.Grids;
using MVZ2Logic.Entities;
using MVZ2Logic.Grids;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Grids;
using PVZEngine.Placements;

namespace MVZ2.GameContent.Placements
{
    public abstract class ContraptionSpawnCondition : SpawnCondition
    {
        public sealed override NamespaceID? GetSpawnError(PlacementDefinition placement, LawnGrid grid, EntityDefinition entity)
        {
            var extraGrids = entity.GetGridsToTake(grid);
            var thisGridError = GetSpawnErrorOfGrid(placement, grid, entity);
            if (thisGridError != null)
                return thisGridError;

            foreach (var extraGrid in extraGrids)
            {
                if (extraGrid == null)
                    return VanillaGridStatus.outOfBounds;
                var error = GetSpawnErrorOfGrid(placement, extraGrid, entity);
                if (error != null)
                    return error;
            }
            return null;
        }
        protected virtual NamespaceID? GetSpawnErrorOfGrid(PlacementDefinition placement, LawnGrid grid, EntityDefinition entity)
        {
            if (grid.IsDisabled())
                return VanillaGridStatus.gridDisabled;
            var layersToTake = entity.GetGridLayersToTake();
            var conflictEntities = layersToTake.Select(l => grid.GetLayerEntity(l)).OfType<Entity>();
            if (conflictEntities.Count() > 0)
            {
                foreach (var ent in conflictEntities)
                {
                    if (ent.IsEntityOf(VanillaObstacleID.gargoyleStatue))
                    {
                        return VanillaGridStatus.notOnStatues;
                    }
                    if (ent.IsEntityOf(VanillaObstacleID.monsterSpawner))
                    {
                        return VanillaGridStatus.notOnSpawners;
                    }
                }
                return VanillaGridStatus.alreadyTaken;
            }
            return null;
        }
    }
}
