#nullable enable // autogenerated

using System.Linq;
using MVZ2.GameContent.Contraptions;
using MVZ2.Vanilla.Grids;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Grids;
using PVZEngine.Placements;

namespace MVZ2.GameContent.Placements
{
    public class DreamSilkSpawnCondition : ContraptionSpawnCondition
    {
        protected override NamespaceID? GetSpawnErrorOfGrid(PlacementDefinition placement, LawnGrid grid, EntityDefinition entity)
        {
            var entities = grid.GetEntities();
            if (entities.Count() <= 0 || !entities.Any(e => DreamSilk.CanSleep(e)))
                return VanillaGridStatus.onlyCanSleep;

            // 被占用。
            return base.GetSpawnErrorOfGrid(placement, grid, entity);
        }
    }
}
