#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.Damages;

namespace MVZ2.GameContent.Projectiles
{
    [EntityBehaviourDefinition(VanillaProjectileNames.BloodBolt)]
    public class BloodBolt : ProjectileBehaviour, IHellfireIgniteBehaviour
    {
        public BloodBolt(string nsp, string name) : base(nsp, name)
        {
        }
        public void Ignite(Entity entity, Entity hellfire, bool cursed)
        {
            var param = entity.GetSpawnParams();
            param.SetProperty(EngineEntityProps.SIZE, entity.GetScaledSize());
            entity.Spawn(VanillaEffectID.smoke, entity.Position, param);
            entity.Die();
            entity.PlaySound(VanillaSoundID.fizz);
        }
        protected override void PostHitEntity(ProjectileHitOutput hitResult, DamageOutput? damage)
        {
            base.PostHitEntity(hitResult, damage);
            var enemy = hitResult.Other;
            if (enemy.Type != EntityTypes.ENEMY)
                return;
            enemy.SoulFreeze(240);
            enemy.InflictDeathMarkBuff(3f, 120, new EntitySourceReference(hitResult.Projectile));
        }
    }
}
