#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;

using MVZ2Logic.Entities;

using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Projectiles
{
    [AutoEntityBehaviourDefinition(VanillaProjectileNames.BloodBolt)]
    public class BloodBolt : EntityBehaviourDefinition, IHellfireIgniteBehaviour
    {
        public BloodBolt(string nsp, string name) : base(nsp, name)
        {
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostHitEntityCallback);
        }
        public void Ignite(Entity entity, Entity hellfire, bool cursed)
        {
            var param = entity.GetSpawnParams();
            param.SetProperty(EngineEntityProps.SIZE, entity.GetScaledSize());
            entity.Spawn(VanillaEffectID.smoke, entity.Position, param);
            entity.Die();
            entity.PlaySound(VanillaSoundID.fizz);
        }
        private void PostHitEntityCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hitResult = param.hit;
            var projectile = hitResult.Projectile;
            if (!projectile.Definition.HasBehaviour(this))
                return;
            var enemy = hitResult.Other;
            if (enemy.Type != EntityTypes.ENEMY)
                return;
            enemy.SoulFreeze(240);
            enemy.InflictDeathMarkBuff(3f, 120, new EntitySourceReference(hitResult.Projectile));
        }
    }
}
