#nullable enable // autogenerated

using MVZ2Logic;
using MVZ2Logic.Definitions;
using MVZ2Logic.Options;

namespace MVZ2.GameContent.Options
{
    [AutoOptionWidgetDefinition(LogicOptionWidgetNames.screenShake)]
    public class ScreenShakeOptionSlider : OptionSliderDefinition
    {
        public ScreenShakeOptionSlider(string nsp, string name) : base(nsp, name)
        {
        }
        public override float GetValue(IOptionContext context)
        {
            return Global.Options.GetShakeAmount();
        }
        public override string GetLabelValue(IOptionContext context, float value)
        {
            return LogicMain.GetFloatPercentageText(value);
        }
        public override void OnValueChanged(IOptionContext context, float value)
        {
            Global.Options.SetShakeAmount(value);
        }

        public override void OnEndEdit(IOptionContext context, float value)
        {
            Global.Options.SetShakeAmount(value);
            Global.Options.SaveOptions();
        }
    }
}
