#nullable enable // autogenerated  
  
using MVZ2.Vanilla.Level;  
using PVZEngine.Definitions;  
using PVZEngine.Level;
using MVZ2Logic.Level;

namespace MVZ2.GameContent.Stages  
{  
    [StageDefinition(VanillaStageNames.HatTrick)]  
    public class HatTrick : IZombiePuzzleStage  
    {  
        public HatTrick(string nsp, string name) : base(nsp, name, VanillaIZombieLayoutID.HatTrick)  
        {  
            this.SetPickaxeCountLimit(2);  // StageDefinition 的重载，可在构造函数中调用  
        }  
  
        public override void OnStart(LevelEngine level)  
        {  
            base.OnStart(level);  
            level.SetPickaxeActive(true);    // 重新启用镐子（Behaviour 的 Start 已经把它关了）  
            level.SetPickaxeRemainCount(2);  // 初始2次  
        }  
    }  
}