#nullable enable // autogenerated

using PVZEngine;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2Logic.Entities
{
    [PropertyRegistryRegion(PropertyRegions.entity)]
    public static class LogicEnemyProps
    {
        private static PropertyMeta<T> Get<T>(string name, T? defaultValue = default, params string[] obsoleteNames)
        {
            return new PropertyMeta<T>(name, defaultValue, obsoleteNames);
        }
        #region 叫声
        public static readonly PropertyMeta<NamespaceID> CRY_SOUND = Get<NamespaceID>("crySound");
        public static NamespaceID? GetCrySound(this Entity enemy)
        {
            return enemy.GetProperty<NamespaceID>(CRY_SOUND);
        }
        #endregion

        #region 叫声音调
        public static readonly PropertyMeta<float> CRY_PITCH = Get<float>("cryPitch");
        public static float GetCryPitch(this Entity entity)
        {
            return entity.GetProperty<float>(CRY_PITCH);
        }
        #endregion

        #region 乘客位置
        public static readonly PropertyMeta<Vector3> PASSENGER_OFFSET = Get<Vector3>("passengerOffset");
        public static Vector3 GetPassengerOffset(this Entity enemy)
        {
            return enemy.GetProperty<Vector3>(PASSENGER_OFFSET);
        }
        #endregion

        #region 预览敌人
        public static readonly PropertyMeta<bool> PREVIEW_ENEMY = Get<bool>("previewEnemy");
        public static void SetPreviewEnemy(this Entity enemy, bool value)
        {
            enemy.SetProperty(PREVIEW_ENEMY, value);
        }
        public static bool IsPreviewEnemy(this Entity enemy)
        {
            return enemy.GetProperty<bool>(PREVIEW_ENEMY);
        }
        #endregion

        #region 假定存活

        public static readonly PropertyMeta<bool> ASSUME_ALIVE = Get<bool>("assume_alive");
        public static bool AssumeAlive(this Entity enemy)
        {
            return enemy.GetProperty<bool>(ASSUME_ALIVE);
        }
        #endregion

        #region 有效敌人
        public static readonly PropertyMeta<bool> NOT_ACTIVE_ENEMY = Get<bool>("notActiveEnemy");
        public static bool IsNotActiveEnemy(this Entity enemy)
        {
            return enemy.GetProperty<bool>(NOT_ACTIVE_ENEMY);
        }
        public static bool IsNotActiveEnemy(this EntityDefinition enemy)
        {
            return enemy.GetProperty<bool>(NOT_ACTIVE_ENEMY);
        }
        #endregion

        #region 克制
        public static readonly PropertyMeta<NamespaceID[]> COUNTER_TAGS = Get<NamespaceID[]>("counter_tags", obsoleteNames: "attackerTags");
        public static NamespaceID[]? GetCounterTags(this EntityDefinition enemy)
        {
            return enemy.GetProperty<NamespaceID[]>(COUNTER_TAGS);
        }
        #endregion
    }
}