#nullable enable // autogenerated  

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Projectiles
{
    [AutoBuffDefinition(VanillaBuffNames.Projectile.hellfireIgnited)]
    public class HellfireIgnitedBuff : BuffDefinition
    {
        public enum FireType
        {
            Normal,     // 普通火焰  
            Cursed,     // 诅咒火焰  
            SoulFreeze  // 灵魂冻结火  
        }

        public HellfireIgnitedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(VanillaEntityProps.IS_FIRE, true));
            AddModifier(new BooleanModifier(LogicEntityProps.IS_LIGHT_SOURCE, true));
            AddModifier(new Vector3Modifier(LogicEntityProps.LIGHT_RANGE, NumberOperator.Add, PROP_LIGHT_RANGE_ADDITION));
            AddModifier(ColorModifier.Override(LogicEntityProps.LIGHT_COLOR, PROP_LIGHT_COLOR));
            AddModifier(new IntModifier(LogicEntityProps.LIGHT_LEVEL, IntegerOperator.Set, PROP_LIGHT_LEVEL)); // 新增：按形态输出光照等级  
            AddTrigger(VanillaLevelCallbacks.POST_PROJECTILE_HIT, PostProjectileHitCallback);
        }
        public override void PostAdd(Buff buff)
        {
            base.PostAdd(buff);
            SetFireType(buff, FireType.Normal);
            UpdateLightRange(buff);
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            UpdateLightRange(buff);
        }
        private void UpdateLightRange(Buff buff)
        {
            var entity = buff.GetEntity();
            float scale = 1;
            if (entity != null)
            {
                var scaledSize = entity.GetScaledSize();
                var scaleVec = scaledSize / DEFAULT_SCALE;
                scale = Mathf.Max(scaleVec.x, scaleVec.y, scaleVec.z);
            }

            // 根据火焰类型调整光源大小  
            float rangeMultiplier = 1f;
            var fireType = GetFireType(buff);
            if (fireType == FireType.SoulFreeze)
            {
                rangeMultiplier = 0.75f; // SoulFreezeFire光源大小为普通火焰的0.75  
            }

            buff.SetProperty(PROP_LIGHT_RANGE_ADDITION, Vector3.one * 60 * scale * rangeMultiplier);
        }
        private void PostProjectileHitCallback(VanillaLevelCallbacks.PostProjectileHitParams param, CallbackResult result)
        {
            var hit = param.hit;
            var damage = param.damage;
            var projectile = hit.Projectile;
            var buffs = projectile.GetBuffs(this);
            float additionalDamage = 0;
            FireType fireType = FireType.Normal;

            foreach (var buff in buffs)
            {
                var type = GetFireType(buff);
                fireType = type;

                switch (type)
                {
                    case FireType.Cursed:
                        additionalDamage += projectile.GetDamage() * 2;
                        break;
                    case FireType.SoulFreeze:
                        additionalDamage += projectile.GetDamage() * 1.5f; // 1.5倍伤害  
                        break;
                    case FireType.Normal:
                    default:
                        additionalDamage += projectile.GetDamage();
                        break;
                }
            }
            if (additionalDamage <= 0)
                return;
            var target = hit.Other;
            var shield = hit.Shield;
            var armorSlot = shield != null ? shield.Slot : null;

            // 根据火焰类型选择伤害效果  
            DamageEffectList damageEffects;
            if (fireType == FireType.SoulFreeze)
            {
                damageEffects = new DamageEffectList(VanillaDamageEffects.ICE, VanillaDamageEffects.SLOW, VanillaDamageEffects.SoulColdFire);
            }
            else
            {
                damageEffects = new DamageEffectList(VanillaDamageEffects.FIRE);
            }

            target.TakeDamage(additionalDamage, damageEffects, projectile, armorSlot);

            bool blocksFire = damage?.WillDamageBlockFire() ?? false;

            if (!blocksFire)
            {
                var entity = projectile;
                var level = entity.Level;

                var splashDamageEffects = new DamageEffectList(VanillaDamageEffects.FIRE, VanillaDamageEffects.MUTE);
                if (fireType == FireType.SoulFreeze)
                {
                    splashDamageEffects = new DamageEffectList(VanillaDamageEffects.FIRE, VanillaDamageEffects.SoulColdFire, VanillaDamageEffects.MUTE);
                }

                var center = entity.GetCenter();
                var radius = 40;
                var faction = entity.GetFaction();

                // 根据火焰类型调整溅射伤害比例  
                float splashRatio = fireType == FireType.SoulFreeze ? 1f / 6f : 2f / 3f;
                var splashAmount = additionalDamage * splashRatio;

                entity.SplashDamage(hit.Collider, center, radius, faction, splashAmount, splashDamageEffects);

                // 根据火焰类型选择特效  
                NamespaceID effectID;
                switch (fireType)
                {
                    case FireType.Cursed:
                        effectID = VanillaEffectID.cursedFireburn;
                        break;
                    case FireType.SoulFreeze:
                        effectID = VanillaEffectID.soulfire;
                        break;
                    case FireType.Normal:
                    default:
                        effectID = VanillaEffectID.fireburn;
                        break;
                }
                entity.Spawn(effectID, entity.Position);
            }
        }

        // 设置火焰类型的方法  
        public static void SetFireType(Buff buff, FireType type)
        {
            switch (type)
            {
                case FireType.Cursed:
                    SetLightColor(buff, LIGHT_COLOR_CURSED);
                    buff.SetProperty(PROP_LIGHT_LEVEL, 4); // 绿  
                    SetCursed(buff, true);
                    break;
                case FireType.SoulFreeze:
                    SetLightColor(buff, LIGHT_COLOR_SOUL_FREEZE);
                    buff.SetProperty(PROP_LIGHT_LEVEL, 5); // 青  
                    SetCursed(buff, false);
                    break;
                case FireType.Normal:
                default:
                    SetLightColor(buff, LIGHT_COLOR);
                    buff.SetProperty(PROP_LIGHT_LEVEL, 2); // 橙  
                    SetCursed(buff, false);
                    break;
            }
            buff.SetProperty(PROP_FIRE_TYPE, (int)type);
        }

        public static FireType GetFireType(Buff buff)
        {
            return (FireType)buff.GetProperty<int>(PROP_FIRE_TYPE);
        }

        // 保留原有的Curse/Uncurse方法以兼容旧代码  
        public static void Curse(Buff buff)
        {
            SetFireType(buff, FireType.Cursed);
        }
        public static void Uncurse(Buff buff)
        {
            SetFireType(buff, FireType.Normal);
        }
        public static void SoulFreeze(Buff buff)
        {
            SetFireType(buff, FireType.SoulFreeze);
        }

        // 保留GetCursed/SetCursed方法以兼容旧代码  
        public static void SetLightColor(Buff buff, Color value) => buff.SetProperty(PROP_LIGHT_COLOR, value);
        public static Color GetLightColor(Buff buff) => buff.GetProperty<Color>(PROP_LIGHT_COLOR);
        public static void SetCursed(Buff buff, bool value) => buff.SetProperty(PROP_CURSED, value);
        public static bool GetCursed(Buff buff) => buff.GetProperty<bool>(PROP_CURSED);

        public static readonly VanillaBuffPropertyMeta<Color> PROP_LIGHT_COLOR = new VanillaBuffPropertyMeta<Color>("lightColor");
        public static readonly VanillaBuffPropertyMeta<Vector3> PROP_LIGHT_RANGE_ADDITION = new VanillaBuffPropertyMeta<Vector3>("light_range_addition");
        public static readonly VanillaBuffPropertyMeta<bool> PROP_CURSED = new VanillaBuffPropertyMeta<bool>("cursed");
        public static readonly VanillaBuffPropertyMeta<int> PROP_FIRE_TYPE = new VanillaBuffPropertyMeta<int>("fireType");
        public const float DEFAULT_SCALE = 32;
        public static readonly Color LIGHT_COLOR = new Color(1, 0.5f, 0);
        public static readonly Color LIGHT_COLOR_CURSED = new Color(0, 1, 0);
        public static readonly Color LIGHT_COLOR_SOUL_FREEZE = new Color(0.9725f, 1f, 1f); // #F8FFFF  
        public static readonly VanillaBuffPropertyMeta<int> PROP_LIGHT_LEVEL = new VanillaBuffPropertyMeta<int>("lightLevel");
    }
}
