#nullable enable // autogenerated

using MVZ2Logic.Conditions;
using PVZEngine;

namespace MVZ2Logic.Maps
{
    [PropertyRegistryRegion(LogicPropertyRegions.mapElement)]
    public static class LogicMapElementProps
    {
        private static PropertyMeta<T> Get<T>(string name, T? defaultValue = default)
        {
            return new PropertyMeta<T>(name, defaultValue);
        }
        #region 形状ID
        public static readonly PropertyMeta<IConditionList> UNLOCK_CONDITIONS = Get<IConditionList>("unlock_conditions");
        public static IConditionList? GetUnlockConditions(this MapElementDefinition definition)
        {
            return definition.GetProperty<IConditionList>(UNLOCK_CONDITIONS);
        }
        public static IConditionList? GetUnlockConditions(this IMapElement entity)
        {
            return entity.GetProperty<IConditionList>(UNLOCK_CONDITIONS);
        }
        public static void SetUnlockConditions(this MapElementDefinition definition, IConditionList? value)
        {
            definition.SetProperty(UNLOCK_CONDITIONS, value);
        }
        #endregion
    }
}