#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Shells;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Shells;

namespace MVZ2.GameContent.Shells
{
    [AutoShellDefinition(VanillaShellNames.shadow)]
    public class ShadowShell : ShellDefinition
    {
        public ShadowShell(string nsp, string name) : base(nsp, name)
        {
            SetProperty(VanillaShellProps.HIT_SOUND, VanillaSoundID.splat);
        }
        public override void EvaluateDamage(DamageInput damageInfo)
        {
            base.EvaluateDamage(damageInfo);
            if (damageInfo.HasEffect(VanillaDamageEffects.LIGHT) ||
                damageInfo.HasEffect(VanillaDamageEffects.FIRE) ||
                damageInfo.HasEffect(VanillaDamageEffects.LIGHTNING))
            {
                damageInfo.Multiply(1.5f);
            }
        }
    }
}
