#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.Vanilla.Entities;
using PVZEngine.Callbacks;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Bosses
{
    [EntityBehaviourDefinition(VanillaEntityBehaviourNames.bossDamageLimit)]
    public partial class BossDamageLimit : BossBehaviour
    {
        public BossDamageLimit(string nsp, string name) : base(nsp, name)
        {
        }
        public override void PreTakeDamage(DamageInput damageInfo, CallbackResult result)
        {
            base.PreTakeDamage(damageInfo, result);
            var entity = damageInfo.Entity;
            if (damageInfo.Amount > 600 && !damageInfo.HasEffect(VanillaDamageEffects.BYPASS_BOSS_ARMOR))
            {
                damageInfo.SetAmount(600);
            }
        }
    }
}
