#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Pickups;
using MVZ2Logic.Level;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Pickups
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.pickupLimitPosition)]
    public class PickupLimitPositionBehaviour : EntityBehaviourDefinition
    {
        public PickupLimitPositionBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Update(Entity pickup)
        {
            base.Update(pickup);
            if (!pickup.IsCollected())
            {
                Vector3 pos = pickup.Position;
                pos.x = Mathf.Clamp(pos.x, LevelPositions.GetPickupBorderX(false), LevelPositions.GetPickupBorderX(true));
                pickup.Position = pos;
            }
        }
    }
}
