#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Pickups
{
    [EntityBehaviourDefinition(VanillaEntityBehaviourNames.gem)]
    public class GemBehaviour : EntityBehaviourDefinition
    {
        public GemBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Update(Entity pickup)
        {
            base.Update(pickup);
            pickup.SetAnimationBool("Rotating", !pickup.IsCollected() && pickup.IsOnGround);
        }
    }
}