#nullable enable // autogenerated

using MukioI18n;
using MVZ2.GameContent.Projectiles;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Definitions;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Localization;
using MVZ2.Vanilla.Projectiles;
using MVZ2.Vanilla.RandomChina;
using MVZ2Logic.Entities;
using PVZEngine.Entities;
using PVZEngine.Level;
using Tools;

namespace MVZ2.GameContent.RandomChinaEvents
{
    [RandomChinaEventDefinition(VanillaRandomChinaEventNames.theChariot)]
    public class TheChariotEvent : RandomChinaEventDefinition
    {
        public TheChariotEvent(string nsp, string path) : base(nsp, path, NAME, DESCRIPTION)
        {
        }
        public override void Run(Entity contraption, RandomGenerator rng)
        {
            var level = contraption.Level;
            foreach (var enemy in level.FindEntities(e => e.Type == EntityTypes.ENEMY && contraption.IsHostile(e) && e.ExistsAndAlive()))
            {
                var pos = enemy.GetCenter();
                var param = contraption.GetShootParams();
                param.projectileID = VanillaProjectileID.missile;
                param.position = contraption.GetCenter();
                param.velocity = (pos - param.position).normalized * 20;
                param.damage = contraption.GetDamage() * 2;
                contraption.ShootProjectile(param);
            }
            contraption.PlaySound(VanillaSoundID.missile);
        }
        [TranslateMsg("随机瓷器事件名称", VanillaStrings.CONTEXT_RANDOM_CHINA_EVENT_NAME)]
        public const string NAME = "XII-战车";
		[TranslateMsg("随机瓷器事件描述", VanillaStrings.CONTEXT_RANDOM_CHINA_EVENT_DESCRIPTION)]
		public const string DESCRIPTION = "向每个敌怪发射一枚导弹";
	}
}
