#nullable enable // autogenerated

using System;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;

namespace MVZ2.UI.Almanac
{
    public class AlmanacDescriptionLinkHandler : MonoBehaviour, IPointerClickHandler
    {
        public void OnPointerClick(PointerEventData eventData)
        {
            // 检查点击的区域是否是文本链接
            int linkIndex = TMP_TextUtilities.FindIntersectingLink(tmpText, Input.mousePosition, eventData.pressEventCamera);
            if (linkIndex != -1)
            {
                TMP_LinkInfo linkInfo = tmpText.textInfo.linkInfo[linkIndex];
                string url = linkInfo.GetLinkID();
                OnLinkClick?.Invoke(url);
            }
        }

        #region 事件
        public event Action<string>? OnLinkClick;
        #endregion

        #region 属性字段
        [SerializeField]
        private TextMeshProUGUI tmpText = null!;
        #endregion

    }
}