#nullable enable // autogenerated

using MVZ2.GameContent.HeldItems;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.HeldItems;
using MVZ2Logic.Inputs;
using MVZ2Logic.Level;
using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Contraptions
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.brickCannon_Trigger)]
    public class Brickcannon_Trigger : EntityEmptyHandClickBehaviour
    {
        public Brickcannon_Trigger(string nsp, string name) : base(nsp, name)
        {
        }
        public override bool CanEmptyHandClick(Entity entity)
        {
            if (entity.State != BrickCannon.STATE_IDLE)
                return false;
            if (BrickCannon.HasNoMissile(entity))
                return false;
            return base.CanEmptyHandClick(entity);
        }
        public override bool IsValidPointerInteraction(Entity entity, PointerInteractionData interaction)
        {
            if (interaction.pointer.type == PointerTypes.TOUCH)
            {
                if (interaction.interaction == PointerInteraction.Release || interaction.interaction == PointerInteraction.Drag)
                    return true;
            }
            else if (interaction.pointer.type == PointerTypes.MOUSE)
            {
                if (interaction.interaction == PointerInteraction.Down)
                    return true;
            }
            return false;
        }
        public override void EmptyHandClick(Entity entity)
        {
            var builder = new HeldItemBuilder(VanillaHeldTypes.brickCannon, 100);
            builder.SetEntityID(entity.ID);
            entity.Level.SetHeldItem(builder);
        }
    }
}