#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml;
using MVZ2.Metas;
using MVZ2Logic;
using PVZEngine;
using PVZEngine.Definitions;
using UnityEngine;

namespace MVZ2.IO
{
    public static class XMLHelper
    {
        public static XmlAttribute CreateAttribute(this XmlNode node, string name, string value)
        {
            var attr = node.OwnerDocument.CreateAttribute(name);
            attr.Value = value;
            node.Attributes.Append(attr);
            return attr;
        }
        public static XmlDocument ReadXmlDocument(this string str)
        {
            using var memory = new MemoryStream();
            using var textWriter = new StreamWriter(memory);
            textWriter.Write(str);
            memory.Seek(0, SeekOrigin.Begin);
            return memory.ReadXmlDocument();
        }
        public static XmlDocument ReadXmlDocument(this Stream stream)
        {
            XmlReaderSettings settings = new XmlReaderSettings();
            settings.IgnoreComments = true;
            using var xmlReader = XmlReader.Create(stream, settings);
            var document = new XmlDocument();
            document.Load(xmlReader);
            return document;
        }
        public static bool HasAttribute(this XmlNode node, string name)
        {
            return node.Attributes[name] != null;
        }
        public static string? GetAttribute(this XmlNode node, string name)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            return attr.Value;
        }
        public static bool? GetAttributeBool(this XmlNode node, string name)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            if (!bool.TryParse(attr.Value, out var value))
                return null;
            return value;
        }
        public static int? GetAttributeInt(this XmlNode node, string name)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            if (!ParseHelper.TryParseInt(attr.Value, out var value))
                return null;
            return value;
        }
        public static float? GetAttributeFloat(this XmlNode node, string name)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            if (!ParseHelper.TryParseFloat(attr.Value, out var value))
                return null;
            return value;
        }
        public static Color? GetAttributeColor(this XmlNode node, string name)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            if (!ColorUtility.TryParseHtmlString(attr.Value, out var value))
                return null;
            return value;
        }
        public static NamespaceID? GetAttributeNamespaceID(this XmlNode node, string name, string defaultNsp)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            if (!NamespaceID.TryParse(attr.Value, defaultNsp, out var value))
                return null;
            return value;
        }
        public static NamespaceID[]? GetAttributeNamespaceIDArray(this XmlNode node, string name, string defaultNsp)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            var list = new List<NamespaceID>();
            foreach (var str in attr.Value.Split(' ', ';'))
            {
                if (NamespaceID.TryParse(str, defaultNsp, out var condition))
                {
                    list.Add(condition);
                }
            }
            return list.ToArray();
        }
        public static SpriteReference? GetAttributeSpriteReference(this XmlNode node, string name, string defaultNsp)
        {
            var attr = node.Attributes[name];
            if (attr == null)
                return null;
            if (!SpriteReference.TryParse(attr.Value, defaultNsp, out var value))
                return null;
            return value;
        }
        public static Gradient? ToGradient(this XmlNode node)
        {
            if (node == null)
                return null;
            var blend = node.GetAttributeBool("blend") ?? false;

            GradientColorKey[] colorKeys;
            var colorKeysNode = node["colorKeys"];
            if (colorKeysNode?.ChildNodes == null || colorKeysNode.ChildNodes.Count <= 0)
            {
                colorKeys = new GradientColorKey[]
                {
                    new GradientColorKey(Color.magenta, 0),
                    new GradientColorKey(Color.black, 0.5f),
                };
            }
            else
            {
                colorKeys = new GradientColorKey[colorKeysNode.ChildNodes.Count];
                for (int i = 0; i < colorKeys.Length; i++)
                {
                    colorKeys[i] = colorKeysNode.ChildNodes[i].ToGradientColorKey();
                }
            }

            GradientAlphaKey[] alphaKeys;
            var alphaKeysNode = node["alphaKeys"];
            if (alphaKeysNode?.ChildNodes == null || alphaKeysNode.ChildNodes.Count <= 0)
            {
                alphaKeys = new GradientAlphaKey[]
                {
                    new GradientAlphaKey(1, 0)
                };
            }
            else
            {
                alphaKeys = new GradientAlphaKey[alphaKeysNode.ChildNodes.Count];
                for (int i = 0; i < alphaKeys.Length; i++)
                {
                    alphaKeys[i] = alphaKeysNode.ChildNodes[i].ToGradientAlphaKey();
                }
            }

            return new Gradient()
            {
                mode = blend ? GradientMode.Blend : GradientMode.Fixed,
                colorKeys = colorKeys,
                alphaKeys = alphaKeys
            };
        }
        public static GradientColorKey ToGradientColorKey(this XmlNode node)
        {
            var col = ColorUtility.TryParseHtmlString(node.GetAttribute("hex"), out var color) ? color : Color.magenta;
            var time = node.GetAttributeFloat("time") ?? 0;
            return new GradientColorKey(col, time);
        }
        public static GradientAlphaKey ToGradientAlphaKey(this XmlNode node)
        {
            var alpha = node.GetAttributeFloat("alpha") ?? 1;
            var time = node.GetAttributeFloat("time") ?? 0;
            return new GradientAlphaKey(alpha, time);
        }
        public static void ModifyEntityBehaviours(this XmlNode node, List<NamespaceID> behaviours, Dictionary<string, object?> properties, string defaultNsp)
        {
            if (node == null)
                return;
            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                var childNode = node.ChildNodes[i];
                if (childNode.Name == "behaviour")
                {
                    childNode.OperateBehaviourList(behaviours, defaultNsp);
                }
                else if (childNode.Name == "properties")
                {
                    childNode.FillBehaviourProperties(properties, defaultNsp);
                }
            }
        }
        public static void OperateBehaviourList(this XmlNode node, List<NamespaceID> behaviours, string defaultNsp)
        {
            var item = EntityBehaviourItem.FromXmlNode(node, defaultNsp);
            if (item == null)
                return;
            switch (item.Operator)
            {
                case BehaviourOperator.Add:
                    if (behaviours.Contains(item.ID))
                    {
                        Log.LogWarning($"Trying to add behaviour {item.ID} to the list which already has this.");
                    }
                    else
                    {
                        behaviours.Add(item.ID);
                    }
                    break;
                case BehaviourOperator.Remove:
                    if (!behaviours.Remove(item.ID))
                    {
                        Log.LogWarning($"Cannot find behaviour {item.ID} to remove.");
                    }
                    break;
                case BehaviourOperator.Replace:
                    if (NamespaceID.IsValid(item.SourceID))
                    {
                        var index = behaviours.IndexOf(item.SourceID);
                        if (index >= 0)
                        {
                            behaviours[index] = item.ID;
                        }
                        else
                        {
                            Log.LogWarning($"Failed to replace behaviour {item.SourceID} to {item.ID}, cannot find the behaviour to replace.");
                        }
                    }
                    else
                    {
                        Log.LogWarning($"Failed to replace behaviour to {item.ID}, the behaviour id to replace is invalid.");
                    }
                    break;
            }
        }
        public static void FillBehaviourProperties(this XmlNode node, Dictionary<string, object?> properties, string defaultNsp)
        {
            var propertyTargetBehaviourID = node.GetAttributeNamespaceID("behaviour", defaultNsp);
            if (!NamespaceID.IsValid(propertyTargetBehaviourID))
                return;
            var propDict = node.ToPropertyDictionary(defaultNsp);
            foreach (var pair in propDict)
            {
                var fullName = PropertyKeyHelper.CombineFullName(propertyTargetBehaviourID.SpaceName, EngineDefinitionTypes.ENTITY_BEHAVIOUR, propertyTargetBehaviourID.Path, pair.Key);
                properties.Add(fullName, pair.Value);
            }
        }
        public static Dictionary<string, object?> ToPropertyDictionary(this XmlNode node, string defaultNsp)
        {
            var properties = new Dictionary<string, object?>();
            if (node == null)
                return properties;
            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                var propNode = node.ChildNodes[i];
                var propKey = propNode.GetAttribute("name");
                if (!string.IsNullOrEmpty(propKey) && propNode.TryToProperty(defaultNsp, out var propValue))
                {
                    properties.Add(propKey, propValue);
                }
                else
                {
                    Debug.LogWarning($"Cannot create property \"{propKey}\" of type \"{propNode.Name}\" from xml node.");
                }
            }
            return properties;
        }
        public static XMLConditionList? GetUnlockConditionsOrObsolete(this XmlNode node, string childNodeName, string fallbackAttributeName, string defaultNsp)
        {
            XMLConditionList? conditions = null;
            var unlockNode = node[childNodeName];
            if (unlockNode != null)
            {
                conditions = XMLConditionList.FromXmlNode(unlockNode, defaultNsp);
            }
            else
            {
                var unlock = node.GetAttributeNamespaceID(fallbackAttributeName, defaultNsp);
                if (NamespaceID.IsValid(unlock))
                {
                    conditions = XMLConditionList.FromSingle(unlock);
                }
            }
            return conditions;
        }
        public static XMLConditionList? GetUnlockConditionsOrObsoleteArray(this XmlNode node, string childNodeName, string fallbackAttributeName, string defaultNsp)
        {
            XMLConditionList? conditions = null;
            var unlockNode = node[childNodeName];
            if (unlockNode != null)
            {
                conditions = XMLConditionList.FromXmlNode(unlockNode, defaultNsp);
            }
            else
            {
                var unlock = node.GetAttributeNamespaceIDArray(fallbackAttributeName, defaultNsp);
                if (unlock != null)
                {
                    conditions = XMLConditionList.FromMultiple(unlock);
                }
            }
            return conditions;
        }

        public static bool TryGetAttributeStruct(this XmlNode node, string name, string type, out object? propValue)
        {
            propValue = null;
            switch (type)
            {
                case "bool":
                    {
                        var value = node.GetAttributeBool(name);
                        if (value.HasValue)
                        {
                            propValue = value.Value;
                            return true;
                        }
                    }
                    break;
                case "int":
                case "integer":
                    {
                        var value = node.GetAttributeInt(name);
                        if (value.HasValue)
                        {
                            propValue = value.Value;
                            return true;
                        }
                    }
                    break;
                case "float":
                    {
                        var value = node.GetAttributeFloat(name);
                        if (value.HasValue)
                        {
                            propValue = value.Value;
                            return true;
                        }
                    }
                    break;
                case "string":
                    {
                        if (!node.HasAttribute(name))
                        {
                            propValue = null;
                            return false;
                        }
                        propValue = node.GetAttribute(name);
                        return true;
                    }
                case "color":
                    {
                        var value = node.GetAttributeColor(name);
                        if (value.HasValue)
                        {
                            propValue = value.Value;
                            return true;
                        }
                    }
                    break;
            }
            return false;
        }
        public static bool TryGetAttributeVector(this XmlNode node, string type, out object? propValue)
        {
            propValue = null;
            switch (type)
            {
                case "vector2":
                    {
                        if (node.TryGetAttributeVector2(out var vec2))
                        {
                            propValue = vec2;
                            return true;
                        }
                    }
                    break;
                case "vector3":
                    {
                        if (node.TryGetAttributeVector3(out var vec3))
                        {
                            propValue = vec3;
                            return true;
                        }
                    }
                    break;
            }
            return false;
        }
        public static bool TryGetAttributeVector2(this XmlNode node, out Vector2 propValue)
        {
            propValue = default;
            var x = node.GetAttributeFloat("x");
            var y = node.GetAttributeFloat("y");
            if (x.HasValue && y.HasValue)
            {
                propValue = new Vector2(x.Value, y.Value);
                return true;
            }
            return false;
        }
        public static bool TryGetAttributeVector3(this XmlNode node, out Vector3 propValue)
        {
            propValue = default;
            var x = node.GetAttributeFloat("x");
            var y = node.GetAttributeFloat("y");
            var z = node.GetAttributeFloat("z");
            if (x.HasValue && y.HasValue && z.HasValue)
            {
                propValue = new Vector3(x.Value, y.Value, z.Value);
                return true;
            }
            return false;
        }
        public static Vector2? GetAttributeVector2(this XmlNode node)
        {
            return TryGetAttributeVector2(node, out var vec) ? vec : null;
        }
        public static Vector3? GetAttributeVector3(this XmlNode node)
        {
            return TryGetAttributeVector3(node, out var vec) ? vec : null;
        }
        public static bool TryGetAttributeNullable(this XmlNode node, string name, string nullAttributeName, string type, string defaultNsp, out object? propValue)
        {
            if (node.GetAttributeBool(nullAttributeName) ?? false)
            {
                propValue = null;
                return true;
            }
            propValue = null;
            switch (type)
            {
                case "id":
                    {
                        var value = node.GetAttributeNamespaceID(name, defaultNsp);
                        bool valid = value != null;
                        if (valid)
                            propValue = value;
                        return valid;
                    }
                case "idArray":
                    {
                        var valueStr = node.GetAttribute(name);
                        if (string.IsNullOrEmpty(valueStr))
                        {
                            propValue = Array.Empty<NamespaceID>();
                        }
                        else
                        {
                            propValue = valueStr.Split(' ').Select(v => NamespaceID.TryParse(v, defaultNsp, out var parsed) ? parsed : null).Where(v => v != null).ToArray();
                        }
                        return true;
                    }
                case "sprite":
                    {
                        var value = node.GetAttributeSpriteReference(name, defaultNsp);
                        if (value != null)
                        {
                            propValue = value;
                            return true;
                        }
                    }
                    break;
            }
            return false;
        }
        public static bool TryToProperty(this XmlNode node, string defaultNsp, out object? propValue)
        {
            var type = node.Name;
            if (node.TryGetAttributeStruct("value", type, out propValue))
            {
                return true;
            }
            if (node.TryGetAttributeVector(type, out propValue))
            {
                return true;
            }
            if (node.TryGetAttributeNullable("value", "null", type, defaultNsp, out propValue))
            {
                return true;
            }
            propValue = null;
            return false;
        }
    }
}
