#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Bosses;
using MVZ2.Vanilla.Modifiers;
using MVZ2.Vanilla.Properties;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using UnityEngine;

namespace MVZ2.GameContent.Bosses
{
    [AutoEntityBehaviourDefinition(VanillaBossNames.lockedChest)]
    public partial class LockedChest : BossBehaviour
    {
        public LockedChest(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(EngineEntityProps.FLIP_X, PROP_FLIP_X, VanillaModifierPriorities.FORCE));
            AddModifier(new FloatModifier(EngineEntityProps.GRAVITY, NumberOperator.Multiply, PROP_GRAVITY_MULTIPLIER));
        }

        #region 回调
        public override void Init(Entity boss)
        {
            base.Init(boss);
            SetPhase(boss, PHASE_2);
            stateMachine.Init(boss);
            stateMachine.StartState(boss, STATE_IDLE);
            boss.CollisionMaskHostile |= EntityCollisionHelper.MASK_PLANT;
        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            stateMachine.UpdateAI(entity);
        }
        protected override void UpdateLogic(Entity entity)
        {
            base.UpdateLogic(entity);
            stateMachine.UpdateLogic(entity);

            var phase = GetPhase(entity);
            entity.SetAnimationInt("Phase", phase);
            entity.SetModelProperty("Phase", phase);
        }
        public override void PostCollision(EntityCollision collision, int state)
        {
            base.PostCollision(collision, state);
            if (state == EntityCollisionHelper.STATE_ENTER)
            {
                var entity = collision.Entity;
                var other = collision.Other;
                if (other.IsEntityOf(VanillaContraptionID.amethystPylon) && other.GetCenter().y < entity.Position.y)
                {
                    if (stateMachine.GetStateNumber(entity) == STATE_SMASH && stateMachine.GetSubState(entity) == HighJumpState.SUBSTATE_FALL)
                    {
                        PrickHighJump(entity, other);
                    }
                }
            }
        }
        #endregion 事件

        public static Entity? SpawnSmashTarget(Entity entity, Vector3 position)
        {
            var target = entity.Spawn(VanillaEffectID.aimTarget, position)?.Let(t =>
            {
                t.SetParent(entity);
            });
            SetSmashTargetID(entity, new EntityID(target));
            return target;
        }
        public static void RemoveSmashTarget(Entity entity)
        {
            var id = GetSmashTargetID(entity);
            var target = id?.GetEntity(entity.Level);
            if (target.ExistsAndAlive())
            {
                target.Remove();
            }
            SetSmashTargetID(entity, null);
        }

        public static int GetPhase(Entity entity) => entity.GetProperty<int>(PROP_PHASE);
        public static void SetPhase(Entity entity, int value) => entity.SetProperty(PROP_PHASE, value);
        public static bool IsFlipX(Entity entity) => entity.GetProperty<bool>(PROP_FLIP_X);
        public static void SetFlipX(Entity entity, bool value) => entity.SetProperty(PROP_FLIP_X, value);
        public static bool HaveBeenPricked(Entity entity) => entity.GetProperty<bool>(PROP_HAVE_BEEN_PRICKED);
        public static void SetHaveBeenPricked(Entity entity, bool value) => entity.SetProperty(PROP_HAVE_BEEN_PRICKED, value);
        public static Vector3 GetTargetPosition(Entity entity) => entity.GetProperty<Vector3>(PROP_TARGET_POSITION);
        public static void SetTargetPosition(Entity entity, Vector3 value) => entity.SetProperty(PROP_TARGET_POSITION, value);
        public static EntityID? GetSmashTargetID(Entity entity) => entity.GetProperty<EntityID>(PROP_SMASH_TARGET_ID);
        public static void SetSmashTargetID(Entity entity, EntityID? value) => entity.SetProperty(PROP_SMASH_TARGET_ID, value);
        public static int GetCoughType(Entity entity) => entity.GetProperty<int>(PROP_COUGH_TYPE);
        public static void SetCoughType(Entity entity, int value) => entity.SetProperty(PROP_COUGH_TYPE, value);

        private static readonly VanillaEntityPropertyMeta<int> PROP_PHASE = new VanillaEntityPropertyMeta<int>("phase");
        private static readonly VanillaEntityPropertyMeta<int> PROP_COUGH_TYPE = new VanillaEntityPropertyMeta<int>("cough_type");
        private static readonly VanillaEntityPropertyMeta<bool> PROP_FLIP_X = new VanillaEntityPropertyMeta<bool>("flip_x");
        private static readonly VanillaEntityPropertyMeta<float> PROP_GRAVITY_MULTIPLIER = new VanillaEntityPropertyMeta<float>("gravity_multiplier", 1f);
        private static readonly VanillaEntityPropertyMeta<bool> PROP_HAVE_BEEN_PRICKED = new VanillaEntityPropertyMeta<bool>("have_been_pricked");
        private static readonly VanillaEntityPropertyMeta<Vector3> PROP_TARGET_POSITION = new VanillaEntityPropertyMeta<Vector3>("target_position");
        private static readonly VanillaEntityPropertyMeta<EntityID> PROP_SMASH_TARGET_ID = new VanillaEntityPropertyMeta<EntityID>("smash_target_id");

        public const float SMASH_DAMAGE_MULTIPLIER = 3;
        public const int STATE_IDLE = VanillaBossStates.IDLE;
        public const int STATE_STUNNED = VanillaBossStates.STUNNED;
        public const int STATE_DEATH = VanillaBossStates.DEATH;

        public const int STATE_JUMP = VanillaBossStates.LOCKED_CHEST_JUMP;
        public const int STATE_CHARGE = VanillaBossStates.LOCKED_CHEST_CHARGE;
        public const int STATE_SMASH = VanillaBossStates.LOCKED_CHEST_SMASH;
        public const int STATE_LOCK = VanillaBossStates.LOCKED_CHEST_LOCK;
        public const int STATE_CRUSHING_LOCK = VanillaBossStates.LOCKED_CHEST_CRUSH_LOCK;

        public const int STATE_SPIT_TRASH = VanillaBossStates.LOCKED_CHEST_SPIT_TRASH;
        public const int STATE_SPECIAL_ATTACK = VanillaBossStates.LOCKED_CHEST_SPECIAL_ATTACK;
        public const int STATE_CAMERA = VanillaBossStates.LOCKED_CHEST_CAMERA;
        public const int STATE_SPIT_ZOMBIE_BLUEPRINTS = VanillaBossStates.LOCKED_CHEST_SPIT_ZOMBIE_BLUEPRINTS;
        public const int STATE_PAY_TO_WIN = VanillaBossStates.LOCKED_CHEST_PAY_TO_WIN;
        public const int STATE_COUGH = VanillaBossStates.LOCKED_CHEST_COUGH;

        public const int ANIMATION_STATE_IDLE = 0;
        public const int ANIMATION_STATE_STUNNED = 2;
        public const int ANIMATION_STATE_DEATH = 3;

        public const int ANIMATION_STATE_JUMP = 10000;
        public const int ANIMATION_STATE_SMASH = 10001;
        public const int ANIMATION_STATE_OPEN_CHEST = 10002;

        public const int PHASE_1 = 0;
        public const int PHASE_2 = 1;
    }
}
