#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaContraptionNames.EXPANDispenser_Totenser)]
    public class EXPANDispenser_Totenser : EXPANDispenser
    {
        public EXPANDispenser_Totenser(string nsp, string name) : base(nsp, name)
        {
        }
    }
}
