#nullable enable // autogenerated

using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Contraptions
{
    [EntityBehaviourDefinition(VanillaContraptionNames.EXPANDispenser_Drivenser)]
    public class EXPANDispenser_Drivenser : EXPANDispenser
    {
        public EXPANDispenser_Drivenser(string nsp, string name) : base(nsp, name)
        {
        }
    }
}
