#nullable enable // autogenerated

using System;
using System.IO;
using MongoDB.Bson.IO;
using MVZ2.IO;
using MVZ2.Managers;
using MVZ2.Metas;
using MVZ2Logic.Games;
using MVZ2Logic.Options;
using MVZ2Logic.Serialization;
using PVZEngine;
using UnityEngine;

namespace MVZ2.Options
{
    public partial class OptionsManager : MonoBehaviour, IGlobalOptions
    {
        public void InitOptions()
        {
            options = new Options();
            InitKeyBindings();
        }
        public void LoadOptions()
        {
            LoadOptionsFromFile();
            UpdateOptions();
        }

        private void LoadOptionsFromFile()
        {
            if (options == null)
                return;
            var path = GetOptionsFilePath();
            if (!File.Exists(path))
                return;
            try
            {
                // 打开文件流
                using var stream = Main.FileManager.OpenFileRead(path);
                using var streamReader = new StreamReader(stream);
                using var jsonReader = new JsonReader(streamReader);

                // 读取首行数据
                var header = LoadOptionsHeader(jsonReader);

                switch (header.version)
                {
                    case VERSION_1:
                        LoadOptionsV1(jsonReader);
                        break;
                    default:
                        stream.Seek(0, SeekOrigin.Begin);
                        LoadOptionsV0(jsonReader);
                        break;
                }
            }
            catch (Exception e)
            {
                Log.LogError($"读取设置文件失败：{e}");
            }
        }
        public void SaveOptionsToFile()
        {
            if (options == null)
                return;
            var path = GetOptionsFilePath();
            try
            {
                FileHelper.ValidateDirectory(path);

                // 打开文件流
                using var stream = Main.FileManager.OpenFileWrite(path);
                using var writer = new StreamWriter(stream);

                // 写入文件首信息
                SaveOptionsHeader(writer);

                // 写入文件内容
                SaveOptionsV1(writer);
            }
            catch (Exception e)
            {
                Log.LogError($"保存设置文件失败：{e}");
            }
        }
        public string GetOptionsFilePath()
        {
            return Path.Combine(Application.persistentDataPath, "options.json");
        }

        #region 选项
        public void SetOptionBool(NamespaceID id, bool value)
        {
            options.SetOptionBool(id, value);
            CallOptionChangedBool(id, value);
            SaveOptionsToFile();
        }
        public void SetOptionInt(NamespaceID id, int value)
        {
            options.SetOptionInt(id, value);
            CallOptionChangedInt(id, value);
            SaveOptionsToFile();
        }
        public void SetOptionFloat(NamespaceID id, float value)
        {
            options.SetOptionFloat(id, value);
            CallOptionChangedFloat(id, value);
            SaveOptionsToFile();
        }
        public void SetOptionString(NamespaceID id, string value)
        {
            options.SetOptionString(id, value);
            CallOptionChangedString(id, value);
            SaveOptionsToFile();
        }
        public void SetOptionID(NamespaceID id, NamespaceID? value)
        {
            options.SetOptionID(id, value);
            CallOptionChangedID(id, value);
            SaveOptionsToFile();
        }

        public bool TryGetOptionBool(NamespaceID id, out bool value) => options.TryGetOptionBool(id, out value);
        public bool TryGetOptionInt(NamespaceID id, out int value) => options.TryGetOptionInt(id, out value);
        public bool TryGetOptionFloat(NamespaceID id, out float value) => options.TryGetOptionFloat(id, out value);
        public bool TryGetOptionString(NamespaceID id, out string value) => options.TryGetOptionString(id, out value);
        public bool TryGetOptionID(NamespaceID id, out NamespaceID? value) => options.TryGetOptionID(id, out value);

        public bool GetOptionBool(NamespaceID id) => TryGetOptionBool(id, out var value) ? value : GetDefaultOptionValueBool(id);
        public int GetOptionInt(NamespaceID id) => TryGetOptionInt(id, out var value) ? value : GetDefaultOptionValueInt(id);
        public float GetOptionFloat(NamespaceID id) => TryGetOptionFloat(id, out var value) ? value : GetDefaultOptionValueFloat(id);
        public string GetOptionString(NamespaceID id) => TryGetOptionString(id, out var value) ? value : GetDefaultOptionValueString(id);
        public NamespaceID? GetOptionID(NamespaceID id) => TryGetOptionID(id, out var value) ? value : GetDefaultOptionValueID(id);


        public bool GetDefaultOptionValueBool(NamespaceID id)
        {
            OptionItemMeta? itemMeta = Main.ResourceManager.GetOptionItemMeta(id);
            if (itemMeta != null && itemMeta.DefaultValue is bool defaultValue)
                return defaultValue;
            return false;
        }
        public int GetDefaultOptionValueInt(NamespaceID id)
        {
            OptionItemMeta? itemMeta = Main.ResourceManager.GetOptionItemMeta(id);
            if (itemMeta != null && itemMeta.DefaultValue is int defaultValue)
                return defaultValue;
            return 0;
        }
        public float GetDefaultOptionValueFloat(NamespaceID id)
        {
            OptionItemMeta? itemMeta = Main.ResourceManager.GetOptionItemMeta(id);
            if (itemMeta != null && itemMeta.DefaultValue is float defaultValue)
                return defaultValue;
            return 0;
        }
        public string GetDefaultOptionValueString(NamespaceID id)
        {
            OptionItemMeta? itemMeta = Main.ResourceManager.GetOptionItemMeta(id);
            if (itemMeta != null && itemMeta.DefaultValue is string defaultValue)
                return defaultValue;
            return string.Empty;
        }
        public NamespaceID? GetDefaultOptionValueID(NamespaceID id)
        {
            OptionItemMeta? itemMeta = Main.ResourceManager.GetOptionItemMeta(id);
            if (itemMeta != null && itemMeta.DefaultValue is NamespaceID defaultValue)
                return defaultValue;
            return null;
        }

        private void UpdateOptions()
        {
            NamespaceID[] metasID = Main.ResourceManager.GetAllOptionItemsID();
            foreach (var id in metasID)
            {
                OptionItemMeta? meta = Main.ResourceManager.GetOptionItemMeta(id);
                if (meta == null)
                    continue;
                switch (meta.Type)
                {
                    case OptionItemType.Boolean:
                        CallOptionChangedBool(id, GetOptionBool(id));
                        break;
                    case OptionItemType.Int:
                        CallOptionChangedInt(id, GetOptionInt(id));
                        break;
                    case OptionItemType.Float:
                        CallOptionChangedFloat(id, GetOptionFloat(id));
                        break;
                    case OptionItemType.String:
                        CallOptionChangedString(id, GetOptionString(id));
                        break;
                    case OptionItemType.ID:
                        CallOptionChangedID(id, GetOptionID(id));
                        break;
                }
            }
        }
        private void CallOptionChangedBool(NamespaceID id, bool value)
        {
            OnOptionChangedBool?.Invoke(id, value);
        }
        private void CallOptionChangedInt(NamespaceID id, int value)
        {
            OnOptionChangedInt?.Invoke(id, value);
        }
        private void CallOptionChangedFloat(NamespaceID id, float value)
        {
            OnOptionChangedFloat?.Invoke(id, value);
        }
        private void CallOptionChangedString(NamespaceID id, string value)
        {
            OnOptionChangedString?.Invoke(id, value);
        }
        private void CallOptionChangedID(NamespaceID id, NamespaceID? value)
        {
            OnOptionChangedID?.Invoke(id, value);
        }
        #endregion

        #region 选项文件首部
        private void SaveOptionsHeader(StreamWriter writer)
        {
            // 写入文件首信息
            var header = new SerializableOptionsHeader(CURRENT_OPTION_VERSION);
            var headerJson = header.ToBson();
            writer.WriteLine(headerJson);
        }
        private SerializableOptionsHeader LoadOptionsHeader(JsonReader reader)
        {
            // 读取首行数据
            return SerializeHelper.ReadBson<SerializableOptionsHeader>(reader);
        }
        #endregion

        #region 选项版本0
        private void LoadOptionsV0(JsonReader reader)
        {
            var seri = SerializeHelper.ReadBson<SerializableOptions>(reader);
            options.LoadFromSerializableV0(seri);
            LoadOptionsFromPrefs();
        }
        private void LoadOptionsFromPrefs()
        {
            LoadOptionFromPrefsID(LogicOptionItemID.difficulty, PREFS_DIFFICULTY);
            LoadOptionFromPrefsBool(LogicOptionItemID.swapTrigger, PREFS_SWAP_TRIGGER);
            LoadOptionFromPrefsBool(LogicOptionItemID.vibration, PREFS_VIBRATION);
            LoadOptionFromPrefsBool(LogicOptionItemID.bloodAndGore, PREFS_BLOOD_AND_GORE);
            LoadOptionFromPrefsBool(LogicOptionItemID.pauseOnFocusLost, PREFS_PAUSE_ON_FOCUS_LOST);
            LoadOptionFromPrefsBool(LogicOptionItemID.skipTalks, PREFS_SKIP_ALL_TALKS);
            LoadOptionFromPrefsBool(LogicOptionItemID.showSponsorNames, PREFS_SHOW_SPONSOR_NAMES);

            LoadOptionFromPrefsFloat(LogicOptionItemID.musicVolume, PREFS_MUSIC_VOLUME);
            LoadOptionFromPrefsFloat(LogicOptionItemID.soundVolume, PREFS_SOUND_VOLUME);
            LoadOptionFromPrefsFloat(LogicOptionItemID.fastForwardMultiplier, PREFS_FASTFORWARD_MULTIPLIER);
            LoadOptionFromPrefsFloat(LogicOptionItemID.animationFrequency, PREFS_ANIMATION_FREQUENCY);
            LoadOptionFromPrefsFloat(LogicOptionItemID.particleAmount, PREFS_PARTICLE_AMOUNT);
            LoadOptionFromPrefsFloat(LogicOptionItemID.shakeAmount, PREFS_SHAKE_AMOUNT);

            LoadOptionFromPrefsString(LogicOptionItemID.language, PREFS_LANGUAGE);
        }
        private void LoadOptionFromPrefsBool(NamespaceID optionID, string prefKey)
        {
            if (!options.ContainsOptionID(optionID) && PlayerPrefs.HasKey(prefKey))
            {
                var prefs = PlayerPrefs.GetInt(prefKey);
                var value = IntToBool(prefs);
                PlayerPrefs.DeleteKey(prefKey);
                options.SetOptionBool(optionID, value);
            }
        }
        private void LoadOptionFromPrefsFloat(NamespaceID optionID, string prefKey)
        {
            if (!options.ContainsOptionID(optionID) && PlayerPrefs.HasKey(prefKey))
            {
                var value = PlayerPrefs.GetFloat(prefKey);
                PlayerPrefs.DeleteKey(prefKey);
                options.SetOptionFloat(optionID, value);
            }
        }
        private void LoadOptionFromPrefsString(NamespaceID optionID, string prefKey)
        {
            if (!options.ContainsOptionID(optionID) && PlayerPrefs.HasKey(prefKey))
            {
                var value = PlayerPrefs.GetString(prefKey);
                PlayerPrefs.DeleteKey(prefKey);
                options.SetOptionString(optionID, value);
            }
        }
        private void LoadOptionFromPrefsID(NamespaceID optionID, string prefKey)
        {
            if (!options.ContainsOptionID(optionID) && PlayerPrefs.HasKey(prefKey))
            {
                var name = PlayerPrefs.GetString(prefKey);
                var value = NamespaceID.Parse(name, Main.BuiltinNamespace);
                PlayerPrefs.DeleteKey(prefKey);
                options.SetOptionID(optionID, value);
            }
        }
        #endregion

        #region 选项版本1
        private void SaveOptionsV1(StreamWriter writer)
        {
            // 写入文件内容
            var body = options.ToSerializable();
            var bodyJson = body.ToBson();
            writer.WriteLine(bodyJson);
        }
        private void LoadOptionsV1(JsonReader reader)
        {
            var body = SerializeHelper.ReadBson<SerializableOptionsV1>(reader);
            options.LoadFromSerializableV1(body);
        }
        #endregion

        #region PlayerPrefs
        private static bool GetPlayerPrefsBool(string key, bool defaultValue)
        {
            if (!PlayerPrefs.HasKey(key))
            {
                PlayerPrefs.SetInt(key, BoolToInt(defaultValue));
            }
            return IntToBool(PlayerPrefs.GetInt(key));
        }
        private static int GetPlayerPrefsInt(string key, int defaultValue)
        {
            if (!PlayerPrefs.HasKey(key))
            {
                PlayerPrefs.SetInt(key, defaultValue);
            }
            return PlayerPrefs.GetInt(key);
        }
        private static string GetPlayerPrefsString(string key, string defaultValue)
        {
            if (!PlayerPrefs.HasKey(key))
            {
                PlayerPrefs.SetString(key, defaultValue);
            }
            return PlayerPrefs.GetString(key);
        }
        private static float GetPlayerPrefsFloat(string key, float defaultValue)
        {
            if (!PlayerPrefs.HasKey(key))
            {
                PlayerPrefs.SetFloat(key, defaultValue);
            }
            return PlayerPrefs.GetFloat(key);
        }
        #endregion

        private static bool IntToBool(int value)
        {
            return value > 0;
        }
        private static int BoolToInt(bool value)
        {
            return value ? 1 : 0;
        }
        public MainManager Main => MainManager.Instance;
        public static event Action<NamespaceID, bool>? OnOptionChangedBool;
        public static event Action<NamespaceID, int>? OnOptionChangedInt;
        public static event Action<NamespaceID, float>? OnOptionChangedFloat;
        public static event Action<NamespaceID, string>? OnOptionChangedString;
        public static event Action<NamespaceID, NamespaceID?>? OnOptionChangedID;

        public const int VERSION_1 = 1;
        public const int CURRENT_OPTION_VERSION = VERSION_1;

        public const string PREFS_LANGUAGE = "Language";
        public const string PREFS_DIFFICULTY = "Difficulty";
        public const string PREFS_SWAP_TRIGGER = "SwapTrigger";
        public const string PREFS_VIBRATION = "Vibration";
        public const string PREFS_BLOOD_AND_GORE = "BloodAndGore";
        public const string PREFS_PAUSE_ON_FOCUS_LOST = "PauseOnFocusLost";
        public const string PREFS_SKIP_ALL_TALKS = "SkipAllTalks";
        public const string PREFS_SHOW_SPONSOR_NAMES = "ShowSponsorNames";

        public const string PREFS_MUSIC_VOLUME = "MusicVolume";
        public const string PREFS_SOUND_VOLUME = "SoundVolume";
        public const string PREFS_FASTFORWARD_MULTIPLIER = "FastForwardMultiplier";
        public const string PREFS_ANIMATION_FREQUENCY = "AnimationFrequency";
        public const string PREFS_PARTICLE_AMOUNT = "ParticleAmount";
        public const string PREFS_SHAKE_AMOUNT = "ShakeAmount";

        private Options options = null!;
    }
}
