#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Seeds
{
    // 重装兵器骑手的升级等级存储（与查找工具 HeavyWeaponBlueprintUtils 分开）：
    // 通用射速等级挂在骑手实体上；超级狙击发射器沿用自身已有的等级存储，其余骑手使用这里的通用等级。
    // 查找骑手时配合 HeavyWeaponBlueprintUtils.FindRider 使用。
    public static class HeavyWeaponUpgradeUtils
    {
        // ===== 通用射速等级 =====
        public static bool CanUpgradeRapid(Entity rider)
        {
            if (rider.IsEntityOf(VanillaContraptionID.MegaSnipenser))
                return MegaSnipenser.CanUpgradeRapid(rider);
            return GetRapidLevel(rider) < MAX_RAPID_LEVEL;
        }
        public static void UpgradeRapid(Entity rider)
        {
            if (rider.IsEntityOf(VanillaContraptionID.MegaSnipenser))
            {
                MegaSnipenser.UpgradeRapid(rider);
                return;
            }
            SetRapidLevel(rider, GetRapidLevel(rider) + 1);
            // 同步关卡备份：骑手被摧毁重生后可凭备份恢复射速等级（如射气球关卡）
            SetLevelRapidBackup(rider.Level, GetRapidLevel(rider));
        }
        public static int GetRapidLevel(Entity rider) => rider.GetBehaviourField<int>(PROP_RAPID_LEVEL);
        public static void SetRapidLevel(Entity rider, int value) => rider.SetBehaviourField(PROP_RAPID_LEVEL, value);

        public const int MAX_RAPID_LEVEL = 4;                    // 占位：通用射速最大等级，可自行调整
        public const float ATTACK_SPEED_PER_RAPID_LEVEL = 0.25f; // 占位：每级攻击速度加成（参照超级狙击发射器）

        // ===== 关卡级射速备份：骑手实体被摧毁重建后，等级从关卡属性恢复 =====
        public static int GetLevelRapidBackup(LevelEngine level) => level.GetProperty<int>(PROP_LEVEL_RAPID_BACKUP);
        public static void SetLevelRapidBackup(LevelEngine level, int value) => level.SetProperty(PROP_LEVEL_RAPID_BACKUP, value);

        private const string PROP_REGION = "heavy_weapon_upgrades";
        [LevelPropertyRegistry(PROP_REGION)]
        public static readonly VanillaLevelPropertyMeta<int> PROP_LEVEL_RAPID_BACKUP = new VanillaLevelPropertyMeta<int>("rapid_level_backup");
        public static readonly VanillaEntityPropertyMeta<int> PROP_RAPID_LEVEL = new VanillaEntityPropertyMeta<int>("heavyWeaponRapidLevel");
    }
}
