#nullable enable // autogenerated

using MVZ2Logic.Entities;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    public abstract class EnemyAnimationBehaviour : EntityBehaviourDefinition, IEnemyAnimationBehaviour
    {
        public EnemyAnimationBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            UpdateAnimationParameters(entity, entity.State);
        }
        public abstract void UpdateAnimationParameters(Entity entity, int state);
        public const int STATE_IDLE = LogicEnemyStates.IDLE;
        public const int STATE_WALK = LogicEnemyStates.WALK;
        public const int STATE_MELEE_ATTACK = LogicEnemyStates.MELEE_ATTACK;
        public const int STATE_CAST = LogicEnemyStates.CAST;
        public const int STATE_DEATH = LogicEnemyStates.DEATH;
        public const int STATE_RANGED_ATTACK = LogicEnemyStates.RANGED_ATTACK;
        public const int STATE_LEAVE = LogicEnemyStates.LEAVE;
    }
}