#nullable enable // autogenerated

using MVZ2.Vanilla.Almanac;
using PVZEngine.Definitions;
using PVZEngine.Placements;

namespace MVZ2.GameContent.Placements
{
    [AutoPlacementDefinition(VanillaPlacementNames.aquatic)]
    public class AquaticPlacement : PlacementDefinition
    {
        public AquaticPlacement(string nsp, string name) : base(nsp, name, VanillaSpawnConditions.aquatic)
        {
            AddMethod(VanillaPlaceMethods.entity);
            AddMethod(VanillaPlaceMethods.firstAid);
            this.SetAlmanacTag(VanillaAlmanacTagID.placementAquatic);
        }
    }
}
