#nullable enable // autogenerated

using MVZ2.Vanilla.Almanac;
using PVZEngine.Definitions;
using PVZEngine.Placements;

namespace MVZ2.GameContent.Placements
{
    [AutoPlacementDefinition(VanillaPlacementNames.buried)]
    public class BuriedPlacement : PlacementDefinition
    {
        public BuriedPlacement(string nsp, string name) : base(nsp, name, VanillaSpawnConditions.buried)
        {
            AddMethod(VanillaPlaceMethods.entity);
            AddMethod(VanillaPlaceMethods.firstAid);
            this.SetAlmanacTag(VanillaAlmanacTagID.placementBuried);
        }
    }
}
