#nullable enable // autogenerated

using PVZEngine.Level;
using PVZEngine.Definitions;

namespace MVZ2.GameContent.Stages
{
    public class GemStageBehaviour : StageBehaviour
    {
        public GemStageBehaviour(StageDefinition stageDef) : base(stageDef)
        {
        }
    }
}
