#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Damages;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;
using UnityEngine;
using MVZ2.GameContent.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEnemyNames.RandomKingSkeleton)]
    public class RandomKingSkeleton : AIEntityBehaviour
    {
        public RandomKingSkeleton(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            SetStateTimer(entity, new FrameTimer(CAST_COOLDOWN));

        }
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);

            if (entity.IsDead)
                return;
            if (entity.State == STATE_MELEE_ATTACK)
                return;
            var stateTimer = GetStateTimer(entity);
            var attackSpeed = entity.GetAttackSpeed();
            if (stateTimer.RunToExpiredAndNotNull(attackSpeed))
            {
                if (entity.State == STATE_CAST)
                {
                    EndCasting(entity);
                }
                else
                {
                    if (!CheckBuildable(entity))
                    {
                        stateTimer.ResetTime(BUILD_DETECT_TIME);
                    }
                    else
                    {
                        StartCasting(entity);
                        BuildBoneWalls(entity);
                    }
                }
            }
        }
        public override void PostDeath(Entity entity, DeathInfo info)
        {
            base.PostDeath(entity, info);
            if (entity.IsCasting())
            {
                EndCasting(entity);
            }
            if (info.Effects.HasEffect(VanillaDamageEffects.REMOVE_ON_DEATH))
                return;

            // ���������ʬ  
            SpawnRandomEnemy(entity);
            entity.Remove();
        }
        public static void SetStateTimer(Entity entity, FrameTimer timer)
        {
            entity.SetBehaviourField(ID, PROP_STATE_TIMER, timer);
        }
        public static FrameTimer? GetStateTimer(Entity entity)
        {
            return entity.GetBehaviourField<FrameTimer>(ID, PROP_STATE_TIMER);
        }

        private void StartCasting(Entity entity)
        {
            entity.SetCasting(true);
            entity.PlaySound(VanillaSoundID.reviveCast);
            var stateTimer = GetStateTimer(entity);
            stateTimer?.ResetTime(CAST_TIME);
        }

        private void EndCasting(Entity entity)
        {
            entity.SetCasting(false);
            var stateTimer = GetStateTimer(entity);
            stateTimer?.ResetTime(CAST_COOLDOWN);
        }

        private bool CheckBuildable(Entity entity)
        {
            return entity.Level.FindEntities(VanillaEnemyID.RandomKingSkeleton).Length < MAX_BONE_WALL_COUNT;
        }

        private void BuildBoneWalls(Entity entity)
        {
            var level = entity.Level;
            int startLine = -1;
            int endLine = 1;
            var lane = entity.GetLane();
            if (lane == 0)
            {
                endLine = 0;
            }
            if (lane == level.GetMaxLaneCount() - 1)
            {
                startLine = 0;
            }

            for (int i = startLine; i <= endLine; i++)
            {
                var x = entity.Position.x + level.GetGridWidth() * 1.5f * entity.GetFacingX();
                var z = entity.Position.z + level.GetGridHeight() * i * 1f;
                var y = level.GetGroundY(x, z);
                Vector3 wallPos = new Vector3(x, y, z);
                entity.SpawnWithParams(VanillaEnemyID.RandomSkeleton, wallPos);
                //if (entity.RNG.Next(3) == 0)
                //{
                //    entity.SpawnWithParams(VanillaEnemyID.RandomKingSkeleton, wallPos);
                //}
            }
        }

        /// <summary>  
        /// ��ԭλ�����������ʬ  
        /// </summary>  
        private void SpawnRandomEnemy(Entity entity)
        {
            var level = entity.Level;
            var rng = entity.RNG;

            // ʹ�ð�������Ȩ������  
            NamespaceID enemyID = GetRandomEnemyID(rng);

            // ��ԭλ�����ɽ�ʬ  
            var spawnParam = entity.GetSpawnParams();
            spawnParam.SetProperty(EngineEntityProps.FACTION, entity.GetFaction());
            entity.Spawn(enemyID, entity.Position, spawnParam);
        }

        /// <summary>  
        /// ����Ȩ�����ѡ��һ����ʬID  
        /// </summary>  
        private NamespaceID GetRandomEnemyID(RandomGenerator rng)
        {
            var index = rng.WeightedRandom(SpawnWeights);
            return SpawnWhitelist[index];
        }



        // ��������ɵĽ�ʬ������  
        private static NamespaceID[] SpawnWhitelist = new NamespaceID[]
        {
    VanillaEnemyID.necromancer,
    VanillaEnemyID.KingSkeleton,
    VanillaEnemyID.EvilMage,
    VanillaEnemyID.KingofReverser,
    VanillaEnemyID.NetherWarrior,
    VanillaEnemyID.NetherArcher,
    VanillaEnemyID.NetherVanguard,
    VanillaEnemyID.AngryReverser,
    VanillaEnemyID.RaiderSkull,
    VanillaEnemyID.WitherSkeletonHorse,
    VanillaEnemyID.WintherMage,

        };

        // ����ÿ����ʬ������Ȩ�أ���ֵԽ�����ɸ���Խ�ߣ�  
        private static int[] SpawnWeights = new int[]
        {
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,

        };

        #region ����
        private const int CAST_COOLDOWN = 420;
        private const int CAST_TIME = 30;
        private const int BUILD_DETECT_TIME = 30;
        private const int MAX_BONE_WALL_COUNT = 15;
        public const int STATE_MELEE_ATTACK = LogicEnemyStates.MELEE_ATTACK;
        public const int STATE_CAST = LogicEnemyStates.CAST;
        public static readonly NamespaceID ID = VanillaEnemyID.necromancer;
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_STATE_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("StateTimer");
        #endregion ����
    }
}
