#nullable enable // autogenerated

using System.Xml;
using MVZ2.IO;
using UnityEngine;

namespace MVZ2.Metas
{
    public class FragmentMeta
    {
        public string Name { get; private set; }
        public Gradient Gradient { get; private set; }
        public static FragmentMeta FromXmlNode(XmlNode node)
        {
            var name = node.GetAttribute("name");
            return new FragmentMeta()
            {
                Name = name,
                Gradient = node.ToGradient()
            };
        }
    }
}
