#nullable enable // autogenerated

using System.Collections.Generic;
using System.Xml;

namespace MVZ2.Metas
{
    public class MusicMetaList
    {
        public MusicMeta[] metas;

        public MusicMetaList(MusicMeta[] metas)
        {
            this.metas = metas;
        }

        public static MusicMetaList FromXmlNode(XmlNode node, string defaultNsp)
        {
            var resources = new List<MusicMeta>();
            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                var meta = MusicMeta.FromXmlNode(node.ChildNodes[i], defaultNsp);
                if (meta != null)
                    resources.Add(meta);
            }
            return new MusicMetaList(resources.ToArray());
        }
    }
}
