#nullable enable // autogenerated

using System.Collections.Generic;
using System.Linq;
using System.Xml;
using MVZ2Logic.Conditions;
using MVZ2Logic.Games;

namespace MVZ2.Metas
{
    public class XMLConditionList : IConditionList
    {
        public XMLConditionList(params XMLCondition[] conditions)
        {
            Conditions = conditions;
        }
        public static XMLConditionList FromXmlNode(XmlNode node, string defaultNsp)
        {
            if (node == null)
                return null;
            List<XMLCondition> conditions = new List<XMLCondition>();
            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                var childNode = node.ChildNodes[i];
                if (childNode.Name == "condition")
                {
                    conditions.Add(XMLCondition.FromXmlNode(childNode, defaultNsp));
                }
            }
            return new XMLConditionList(conditions.ToArray());
        }

        public bool MeetsConditions(IGlobalSaveData save)
        {
            return Conditions.Any(c => c.MeetsCondition(save));
        }
        public XMLCondition[] Conditions { get; private set; }
    }
}
