#nullable enable // autogenerated  
  
using System;  
using System.Collections.Generic;  
using System.Linq;  
using System.Xml;  
using MVZ2.IO;  
using MVZ2Logic.Conditions;  
using MVZ2Logic.Games;  
using PVZEngine;  
  
namespace MVZ2.Metas  
{  
    public class XMLCondition : ICondition  
    {  
        public XmlNode ToXmlNode(string name, XmlDocument document)  
        {  
            XmlNode node = document.CreateElement(name);  
            if (Required != null && Required.Length > 0)  
            {  
                node.CreateAttribute("required", string.Join(' ', Required.Select(e => e.ToString())));  
            }  
            if (RequiredNot != null && RequiredNot.Length > 0)  
            {  
                node.CreateAttribute("requiredNot", string.Join(' ', RequiredNot.Select(e => e.ToString())));  
            }  
            if (RequiredGroups != null && RequiredGroups.Length > 0)  
            {  
                node.CreateAttribute("requiredGroups", string.Join(' ', RequiredGroups.Select(e => e.ToString())));  
            }  
            if (RequiredNotGroups != null && RequiredNotGroups.Length > 0)  
            {  
                node.CreateAttribute("requiredNotGroups", string.Join(' ', RequiredNotGroups.Select(e => e.ToString())));  
            }  
            // 新增：序列化日期条件  
            if (Dates != null && Dates.Length > 0)  
            {  
                node.CreateAttribute("date", string.Join(' ', Dates.Select(d => $"{d.month}/{d.day}")));  
            }  
            if (DatesNot != null && DatesNot.Length > 0)  
            {  
                node.CreateAttribute("dateNot", string.Join(' ', DatesNot.Select(d => $"{d.month}/{d.day}")));  
            }  
            return node;  
        }  
        public static XMLCondition FromXmlNode(XmlNode node, string defaultNsp)  
        {  
            var required = node.GetAttributeNamespaceIDArray("required", defaultNsp);  
            var requiredNot = node.GetAttributeNamespaceIDArray("requiredNot", defaultNsp);  
            var requiredGroups = node.GetAttributeNamespaceIDArray("requiredGroups", defaultNsp);  
            var requiredNotGroups = node.GetAttributeNamespaceIDArray("requiredNotGroups", defaultNsp);  
            // 新增：解析日期条件  
            var dates = ParseDates(node.GetAttribute("date"));  
            var datesNot = ParseDates(node.GetAttribute("dateNot"));  
            return new XMLCondition()  
            {  
                Required = required,  
                RequiredNot = requiredNot,  
                RequiredGroups = requiredGroups,  
                RequiredNotGroups = requiredNotGroups,  
                Dates = dates,  
                DatesNot = datesNot,  
            };  
        }  
        public static XMLCondition FromSingle(NamespaceID id)  
        {  
            return new XMLCondition()  
            {  
                Required = new NamespaceID[] { id },  
            };  
        }  
        public static XMLCondition FromMultiple(NamespaceID[] id)  
        {  
            return new XMLCondition()  
            {  
                Required = id,  
            };  
        }  
        public bool MeetsCondition(IGlobalSaveData save)  
        {  
            // 现有：解锁检查  
            if (Required != null && Required.Any(c => !save.IsUnlocked(c)))  
                return false;  
            if (RequiredGroups != null && RequiredGroups.Any(c => !save.IsGroupUnlocked(c)))  
                return false;  
            if (RequiredNot != null && RequiredNot.Any(c => save.IsUnlocked(c)))  
                return false;  
            if (RequiredNotGroups != null && RequiredNotGroups.Any(c => save.IsGroupUnlocked(c)))  
                return false;  
            // 新增：日期检查  
            var now = DateTime.Now;  
            if (Dates != null && !Dates.Any(d => d.month == now.Month && d.day == now.Day))  
                return false;  
            if (DatesNot != null && DatesNot.Any(d => d.month == now.Month && d.day == now.Day))  
                return false;  
            return true;  
        }  
  
        // 新增：解析 "4/1" 或 "4/1 12/25"（空格分隔多个日期）  
        private static (int month, int day)[]? ParseDates(string? value)  
        {  
            if (string.IsNullOrEmpty(value))  
                return null;  
            var parts = value.Split(' ', StringSplitOptions.RemoveEmptyEntries);  
            var result = new List<(int, int)>();  
            foreach (var part in parts)  
            {  
                var split = part.Split('/');  
                if (split.Length == 2  
                    && int.TryParse(split[0], out var month)  
                    && int.TryParse(split[1], out var day))  
                {  
                    result.Add((month, day));  
                }  
            }  
            return result.Count > 0 ? result.ToArray() : null;  
        }  
  
        public NamespaceID[]? Required { get; set; }  
        public NamespaceID[]? RequiredNot { get; set; }  
        public NamespaceID[]? RequiredGroups { get; set; }  
        public NamespaceID[]? RequiredNotGroups { get; set; }  
        // 新增  
        public (int month, int day)[]? Dates { get; set; }  
        public (int month, int day)[]? DatesNot { get; set; }  
    }  
}