#nullable enable // autogenerated

using MVZ2.Vanilla.Enemies;
using MVZ2.Vanilla.Entities;
using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEntityBehaviourNames.napstablook_State)]
    public class Napstablook_StateBehaviour : EnemyStateBehaviour
    {
        public Napstablook_StateBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        public override int GetAnimationState(int state)
        {
            switch (state)
            {
                case STATE_ANGRY:
                    return ANIMATION_STATE_ANGRY;
            }
            return base.GetAnimationState(state);
        }
        protected override int GetActiveState(Entity enemy)
        {
            if (Napstablook.IsAngry(enemy))
            {
                return STATE_ANGRY;
            }
            return base.GetActiveState(enemy);
        }
        public const int STATE_ANGRY = VanillaEnemyStates.NAPSTABLOOK_ANGRY;
        public const int ANIMATION_STATE_ANGRY = EnemyStateBehaviour.ANIMATION_STATE_PRIVATE + 0;
    }
}
