#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;

using PVZEngine.Definitions;
using PVZEngine.Entities;

namespace MVZ2.GameContent.Enemies
{
    [AutoEntityBehaviourDefinition(VanillaEntityBehaviourNames.skeleton_State)]
    public class Skeleton_StateBehaviour : EnemyStateBehaviour
    {
        public Skeleton_StateBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
        protected override int GetActiveState(Entity enemy)
        {
            if (enemy.Target.ExistsAndAlive())
            {
                return STATE_RANGED_ATTACK;
            }
            return base.GetActiveState(enemy);
        }
    }
}
