#nullable enable // autogenerated

using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Level
{
    [AutoBuffDefinition(VanillaBuffNames.Level.levelEnemiesCleared)]
    public class LevelEnemiesClearedBuff : BuffDefinition
    {
        public LevelEnemiesClearedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(LogicStageProps.NO_ENERGY, true));
            AddModifier(new BooleanModifier(LogicLevelProps.ALL_ENEMIES_CLEARED, true));
        }
    }
}