#nullable enable // autogenerated  

using MVZ2.GameContent.Buffs.Contraptions;
using MVZ2.GameContent.Buffs.Projectiles;
using MVZ2.Vanilla.Projectiles;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using Tools;

namespace MVZ2.GameContent.Contraptions
{
    [AutoEntityBehaviourDefinition(VanillaContraptionNames.FireDispenser)]
    public class FireDispenser : DispenserFamily
    {
        public FireDispenser(string nsp, string name) : base(nsp, name)
        {
        }

        public override void Init(Entity entity)
        {
            base.Init(entity);
            InitShootTimer(entity);
            var evocationTimer = new FrameTimer(120);
            SetEvocationTimer(entity, evocationTimer);
            SetFireLevel(entity, 0);
        }
        public override bool CanTrigger(Entity entity)
        {
            return base.CanTrigger(entity);
        }
        
        protected override void UpdateAI(Entity entity)
        {
            base.UpdateAI(entity);
            if (!entity.IsEvoked())
            {
                ShootTick(entity);
                return;
            }

            EvokedUpdate(entity);
        }

        public override Entity? Shoot(Entity entity)
        {
            int fireLevel = GetFireLevel(entity);
            var param = entity.GetShootParams();

            entity.TriggerAnimation("Shoot");
            var arrow = entity.ShootProjectile(param);

            // 根据火焰形态添加点燃 buff  
            if (arrow != null)
            {
                switch (fireLevel)
                {
                    case 0:
                        // 形态0：普通火焰效果  
                        arrow.AddBuff<HellfireIgnitedBuff>();
                        break;
                    case 1:
                        // 形态1：诅咒火焰效果 
                        var fireBuff = arrow.AddBuff<HellfireIgnitedBuff>();
                        HellfireIgnitedBuff.Curse(fireBuff);
                        break;
                    case 2:
                        // 形态2：骨灵冷火效果
                        var fireBuff2 = arrow.AddBuff<HellfireIgnitedBuff>();
                        HellfireIgnitedBuff.SoulFreeze(fireBuff2);
                        break;
                }
            }

            return arrow;

            
        }

        public static int GetFireLevel(Entity entity)
        {
            return entity.GetProperty<int>(PROP_FIRELEVEL);
        }

        public static void SetFireLevel(Entity entity, int level)
        {
            entity.SetProperty(PROP_FIRELEVEL, level); // 设置 Entity 属性（用于 C# 读取）    
            entity.SetModelProperty("FIRELEVEL", level); // 设置 Model 属性（用于贴图切换）  

            entity.RemoveBuffs<FireDispenserCursedBuff>();
            entity.RemoveBuffs<FireDispenserSoulFireBuff>();

            // 根据等级添加对应的 buff  
            switch (level)
            {
                case 1:
                    entity.AddBuff<FireDispenserCursedBuff>();
                    break;
                case 2:
                    entity.AddBuff<FireDispenserSoulFireBuff>();
                    break;
                case 0:
                    // 形态0不需要buff  
                    break;
            }
        }

        protected override void OnTrigger(Entity entity)
        {
            base.OnTrigger(entity);
            int currentLevel = GetFireLevel(entity);
            int nextLevel = (currentLevel + 1) % 3;
            SetFireLevel(entity, nextLevel);
        }

        private static readonly VanillaEntityPropertyMeta<int> PROP_FIRELEVEL =
            new VanillaEntityPropertyMeta<int>("FIRELEVEL");


        private void EvokedUpdate(Entity entity)
        {
            var evocationTimer = GetEvocationTimer(entity);
            if (evocationTimer == null)
                return;
            evocationTimer.Run();
            if (evocationTimer.PassedInterval(2))
            {
                // 直接调用基类方法  
                var projectile = Shoot(entity);
                if (projectile != null)
                    projectile.Velocity *= 2;
            }
            if (evocationTimer.Expired)
            {
                entity.SetEvoked(false);
                var shootTimer = GetShootTimer(entity);
                shootTimer?.Reset();
            }
        }

        protected override void OnEvoke(Entity entity)
        {
            base.OnEvoke(entity);
            var evocationTimer = GetEvocationTimer(entity);
            evocationTimer?.Reset();
            entity.SetEvoked(true);
        }

        public static FrameTimer? GetEvocationTimer(Entity entity) =>
            entity.GetBehaviourField<FrameTimer>(ID, PROP_EVOCATION_TIMER);

        public static void SetEvocationTimer(Entity entity, FrameTimer timer) =>
            entity.SetBehaviourField(ID, PROP_EVOCATION_TIMER, timer);

        private static readonly NamespaceID ID = VanillaContraptionID.FireDispenser;
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_EVOCATION_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("EvocationTimer");
    }
}