#nullable enable // autogenerated

namespace MVZ2.Metas
{
    public class AlmanacVariableReferenceConstant : AlmanacVariableReference
    {
        public double value;

        public AlmanacVariableReferenceConstant(double value)
        {
            this.value = value;
        }
        public override object? GetVariableValue(AlmanacVariableContext context)
        {
            return value;
        }
    }
}
