#nullable enable // autogenerated

using PVZEngine.Entities;

namespace MVZ2.Vanilla.Entities
{
    public abstract class EffectBehaviour : EntityBehaviourDefinition
    {
        protected EffectBehaviour(string nsp, string name) : base(nsp, name)
        {
        }
    }
}
