#nullable enable // autogenerated

using PVZEngine;

namespace MVZ2Logic.Definitions
{
    public class AutoSeedOptionDefinitionAttribute : DefinitionAttribute
    {
        public AutoSeedOptionDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.SEED_OPTION)
        {
        }
    }
    public class AutoNoteDefinitionAttribute : DefinitionAttribute
    {
        public AutoNoteDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.NOTE)
        {
        }
    }
    public class AutoArtifactDefinitionAttribute : DefinitionAttribute
    {
        public AutoArtifactDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.ARTIFACT)
        {
        }
    }
    public class AutoHeldItemDefinitionAttribute : DefinitionAttribute
    {
        public AutoHeldItemDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.HELD_ITEM)
        {
        }
    }
    public class AutoHeldItemBehaviourDefinitionAttribute : DefinitionAttribute
    {
        public AutoHeldItemBehaviourDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.HELD_ITEM_BEHAVIOUR)
        {
        }
    }
    public class AutoIZombieLayoutDefinitionAttribute : DefinitionAttribute
    {
        public AutoIZombieLayoutDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.I_ZOMBIE_LAYOUT)
        {
        }
    }
    public class AutoCommandDefinitionAttribute : DefinitionAttribute
    {
        public AutoCommandDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.COMMAND)
        {
        }
    }
    public class AutoOptionWidgetDefinitionAttribute : DefinitionAttribute
    {
        public AutoOptionWidgetDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.OPTION_WIDGET)
        {
        }
    }
    public class AutoMapElementDefinitionAttribute : DefinitionAttribute
    {
        public AutoMapElementDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.MAP_ELEMENT)
        {
        }
    }
    public class AutoMapElementBehaviourDefinitionAttribute : DefinitionAttribute
    {
        public AutoMapElementBehaviourDefinitionAttribute(string name) : base(name, LogicDefinitionTypes.MAP_ELEMENT_BEHAVIOUR)
        {
        }
    }
}
