#nullable enable // autogenerated

using UnityEngine;

namespace MVZ2.UI.Level
{
    public class StarshardPanelPoint : MonoBehaviour
    {
        public void SetHighlight(bool highlight)
        {
            darkGameObject.SetActive(!highlight);
            highlightGameObject.SetActive(highlight);
        }
        [SerializeField]
        private GameObject darkGameObject = null!;
        [SerializeField]
        private GameObject highlightGameObject = null!;
    }
}
