#nullable enable // autogenerated

using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Armors
{
    [AutoBuffDefinition(VanillaBuffNames.Armor.iZombieSkeletonWarriorArmor)]
    public class IZombieSkeletonWarriorArmorBuff : BuffDefinition
    {
        public IZombieSkeletonWarriorArmorBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new ArmorMaxHealthModifier(NumberOperator.Multiply, 3f));
        }
    }
}
