#nullable enable // autogenerated

using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Entities
{

    [AutoBuffDefinition(VanillaBuffNames.Entity.draggedByBalloon)]
    public class DraggedByBalloonBuff : BuffDefinition
    {
        public DraggedByBalloonBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(EngineEntityProps.GRAVITY, NumberOperator.Multiply, 0));
        }
    }
}
