#nullable enable // autogenerated

using MVZ2.GameContent.Effects;
using MVZ2.GameContent.Fragments;
using MVZ2.GameContent.Models;
using MVZ2.GameContent.Shells;
using MVZ2.Vanilla.Audios;
using MVZ2.Vanilla.Effects;
using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using MVZ2.Vanilla.Models;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Models;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Entities
{
    [AutoBuffDefinition(VanillaBuffNames.Entity.petrified)]
    public class PetrifiedBuff : BuffDefinition
    {
        public PetrifiedBuff(string nsp, string name) : base(nsp, name)
        {
            AddModelInsertion(LogicModelHelper.ANCHOR_ROOT, VanillaModelKeys.petrifiedFeet, VanillaModelID.petrifiedFeet);
            AddModifier(new BooleanModifier(VanillaEntityProps.AI_FROZEN, true));
            AddModifier(new BooleanModifier(LogicEntityProps.REMOVE_ON_DEATH, true));
            AddModifier(new BooleanModifier(LogicEntityProps.NO_DEATH_EFFECTS, true));
            AddModifier(new BooleanModifier(LogicEntityProps.KILL_BY_PICKAXE, true));
            AddModifier(new NamespaceIDModifier(EngineEntityProps.SHELL, SetOperator.Set, VanillaShellID.stone));
            AddModifier(new FloatModifier(LogicEntityProps.ANIMATION_SPEED, NumberOperator.Multiply, 0));
            AddModifier(new Vector3Modifier(LogicEntityProps.HSV_OFFSET, NumberOperator.Add, new Vector3(0, -100, 0)));
            AddTrigger(LevelCallbacks.POST_ENTITY_DEATH, PostEntityDeathCallback);
        }
        public override void OnCreate(Buff buff)
        {
            base.OnCreate(buff);
            buff.SetProperty(PROP_TIMER, new FrameTimer(0));
        }
        public override void PostRemove(Buff buff)
        {
            base.PostRemove(buff);
            var entity = buff.GetEntity();
            if (entity != null && entity.Exists())
            {
                entity.Spawn(VanillaEffectID.petrifiedShards, entity.Position);
                entity.PlaySound(VanillaSoundID.rockCrumble);
            }
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var timer = buff.GetProperty<FrameTimer>(PROP_TIMER);
            if (timer == null)
            {
                buff.Remove();
                return;
            }
            timer.Run();
            if (timer.Expired)
            {
                buff.Remove();
                return;
            }
            var entity = buff.GetEntity();
            if (entity == null || !entity.Exists() || entity.IsDead)
            {
                buff.Remove();
                return;
            }
        }
        private void PostEntityDeathCallback(LevelCallbacks.EntityDeathParams param, CallbackResult result)
        {
            var entity = param.entity;
            if (!entity.HasBuff(this))
                return;
            entity.CreateFragmentAndPlay(VanillaFragmentID.furnace);
            entity.PlaySound(VanillaSoundID.rockCrumble);
        }
        public static void SetTime(Buff buff, int value)
        {
            var timer = buff.GetProperty<FrameTimer>(PROP_TIMER);
            if (timer == null)
                return;
            timer.ResetTime(value);
        }
        public static void MaxTime(Buff buff, int value)
        {
            var timer = buff.GetProperty<FrameTimer>(PROP_TIMER);
            if (timer == null || timer.Frame > value)
                return;
            timer.ResetTime(value);
        }
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("Timer");
    }
}
