#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Models;
using MVZ2.Vanilla.Callbacks;
using MVZ2.Vanilla.Models;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Models;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Callbacks;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;
using Tools;
using UnityEngine;

namespace MVZ2.GameContent.Buffs.Entities
{

    [AutoBuffDefinition(VanillaBuffNames.Entity.transfenserGlowing)]
    public class TransfenserGlowingBuff : BuffDefinition
    {
        public TransfenserGlowingBuff(string nsp, string name) : base(nsp, name)
        {
            AddModelInsertion(LogicModelHelper.ANCHOR_CENTER, VanillaModelKeys.glowingParticles, VanillaModelID.glowingParticles);
            AddModifier(new BooleanModifier(LogicEntityProps.IS_LIGHT_SOURCE, true));
            AddModifier(ColorModifier.Override(LogicEntityProps.LIGHT_COLOR, Color.yellow));
            AddModifier(new Vector3Modifier(LogicEntityProps.LIGHT_RANGE, NumberOperator.Set, Vector3.one * 256f));
            AddModifier(new ColorModifier(EngineEntityProps.COLOR_OFFSET, new Color(1, 1, 0, 0.2f)) { NoStack = true });
            AddTrigger(VanillaLevelCallbacks.PRE_ENTITY_TAKE_DAMAGE, PreEntityTakeDamageCallback, priority: VanillaCallbackPriorities.MULTIPLY);

            //EXPAND
            AddModifier(new IntModifier(LogicEntityProps.LIGHT_LEVEL, IntegerOperator.Set, 3));
        }
        public override void OnCreate(Buff buff)
        {
            base.OnCreate(buff);
            SetTimer(buff, TimerHelper.NewSecondTimer(DEFAULT_SECONDS));
        }
        public override void PostUpdate(Buff buff)
        {
            base.PostUpdate(buff);
            var timer = GetTimer(buff);
            if (timer.RunToExpiredOrNull())
            {
                buff.Remove();
            }
        }
        public static FrameTimer? GetTimer(Buff buff)
        {
            return buff.GetProperty<FrameTimer>(PROP_TIMER);
        }
        public static void SetTimer(Buff buff, FrameTimer? value)
        {
            buff.SetProperty(PROP_TIMER, value);
        }
        public static void ResetTime(Buff buff, int frames)
        {
            var timer = GetTimer(buff);
            if (timer == null)
                return;
            timer.ResetTime(frames);
        }
        public static void MaxTime(Buff buff, int frames)
        {
            var timer = GetTimer(buff);
            if (timer == null || timer.Frame >= frames)
                return;
            timer.ResetTime(frames);
        }
        private void PreEntityTakeDamageCallback(VanillaLevelCallbacks.PreTakeDamageParams param, CallbackResult result)
        {
            var input = param.input;
            var entity = input.Entity;
            if (entity.HasBuff(this))
            {
                if (input.Effects.HasEffect(VanillaDamageEffects.FIRE))
                {
                    input.Multiply(2f);
                }
                else
                {
                    input.Multiply(DAMAGE_MULTIPLIER);
                }
            }
        }
        public const float DEFAULT_SECONDS = 0f;
        public const float DAMAGE_MULTIPLIER = 1.25f;
        public static readonly VanillaBuffPropertyMeta<FrameTimer> PROP_TIMER = new VanillaBuffPropertyMeta<FrameTimer>("timer");
    }
}
