#nullable enable // autogenerated

using PVZEngine.Level;

namespace PVZEngine.Buffs
{
    public interface IBuffTarget : ILevelObject
    {
        IBuffList Buffs { get; }
        BuffReference GetBuffReference(Buff buff);
    }
}
