#nullable enable // autogenerated  

using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Projectiles;
using MVZ2Logic.Level;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class CatapultDetector : Detector
    {
        protected override Bounds GetDetectionBounds(Entity self)
        {
            var shootOffset = self.GetShotOffset();
            shootOffset = self.ModifyShotOffset(shootOffset);
            var source = self.Position + shootOffset;
            var projectileSize = GetProjectileSize(self, Vector3.one * 32);
            var range = self.GetRange();

            var sizeX = range < 0 ? 800 : range;
            if (self.GetFacingX() > 0)
            {
                var limitedRange = LevelPositions.GetAttackBorderX(true) - source.x;
                sizeX = Mathf.Min(sizeX, limitedRange);
            }

            // 顶部封顶在发射点之上 MAX_ATTACK_HEIGHT，底部保留原来的向下覆盖  
            var maxY = source.y + MAX_ATTACK_HEIGHT;
            var minY = source.y - 500;
            float sizeY = maxY - minY;

            var sizeZ = projectileSize.z;
            var centerX = source.x + sizeX * 0.5f * self.GetFacingX();
            float centerY = (minY + maxY) * 0.5f;
            var centerZ = source.z;


            return new Bounds(new Vector3(centerX, centerY, centerZ), new Vector3(sizeX, sizeY, sizeZ));
        }
        // 相对于发射点，允许攻击的最大高度  
        public const float MAX_ATTACK_HEIGHT = 120;
    }
}
