#nullable enable // autogenerated

using MVZ2.Vanilla.Detections;
using MVZ2.Vanilla.Entities;

using PVZEngine.Entities;

using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class HackerDetector : Detector
    {
        protected override Bounds GetDetectionBounds(Entity self)
        {
            var source = self.Position;

            var sizeX = self.GetRange();
            var centerX = source.x + sizeX * 0.5f * self.GetFacingX();

            var sizeY = 1000;
            var centerY = source.y;

            var sizeZ = self.Level.GetGridHeight();
            var centerZ = source.z;

            return new Bounds(new Vector3(centerX, centerY, centerZ), new Vector3(sizeX, sizeY, sizeZ));
        }
        public override bool ValidateTarget(DetectionParams self, Entity target)
        {
            if (target.Type != EntityTypes.PLANT)
                return false;
            if (!target.CanDeactive() || target.IsAIFrozen())
                return false;
            return base.ValidateTarget(self, target);
        }
    }
}
