#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Detections;
using PVZEngine.Entities;
using UnityEngine;

namespace MVZ2.GameContent.Detections
{
    public class SkywardBeaconDetector : Detector
    {
        protected override Bounds GetDetectionBounds(Entity self)
        {
            var targetPosition = SkywardBeacon.GetStrikePosition(self);
            var beamDef = GetEntityDefinition(self.Level, VanillaEffectID.skywardBeam);
            var size = beamDef?.GetSize() ?? new Vector3(64, 800, 64);
            var center = targetPosition;
            center.y = size.y * 0.5f;
            return new Bounds(center, size);
        }
    }
}
