#nullable enable // autogenerated

using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Level
{
    [AutoBuffDefinition(VanillaBuffNames.Level.skywardNight)]
    public class SkywardNightBuff : BuffDefinition
    {
        public SkywardNightBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new IntModifier(LogicLevelProps.DAY_NIGHT_CYCLE_OVERRIDE, IntegerOperator.Set, LogicDayNightCycles.NIGHT));
        }
    }
}
