#nullable enable // autogenerated

using System.Collections.Generic;
using System.Xml;
using MVZ2.IO;
using PVZEngine;

namespace MVZ2.Metas
{
    public class ProductStageMeta
    {
        public string Text { get; private set; } = string.Empty;
        public int Price { get; private set; }
        public NamespaceID? Unlocks { get; private set; }
        public XMLConditionList? Conditions { get; private set; }
        public ProductStatMeta[]? Stats { get; private set; }
        public static ProductStageMeta FromXmlNode(XmlNode node, string defaultNsp)
        {
            var text = node.GetAttribute("text") ?? string.Empty;
            var price = node.GetAttributeInt("price") ?? 0;
            var unlocks = node.GetAttributeNamespaceID("unlocks", defaultNsp);

            XMLConditionList? conditions = null;
            var conditionsNode = node["conditions"];
            if (conditionsNode != null)
            {
                conditions = XMLConditionList.FromXmlNode(conditionsNode, defaultNsp);
            }

            // Stats.
            var stats = new List<ProductStatMeta>();
            for (int i = 0; i < node.ChildNodes.Count; i++)
            {
                var childNode = node.ChildNodes[i];
                if (childNode.Name == "stat")
                {
                    var stat = ProductStatMeta.FromXmlNode(childNode, defaultNsp);
                    if (stat != null)
                    {
                        stats.Add(stat);
                    }
                }
            }

            return new ProductStageMeta()
            {
                Text = text,
                Price = price,
                Unlocks = unlocks,
                Conditions = conditions,
                Stats = stats.ToArray()
            };
        }
    }
    public class ProductStatMeta
    {
        public NamespaceID? Category { get; private set; }
        public NamespaceID? Entry { get; private set; }
        public long Value { get; private set; }
        public static ProductStatMeta? FromXmlNode(XmlNode node, string defaultNsp)
        {
            var category = node.GetAttributeNamespaceID("category", defaultNsp);
            var entry = node.GetAttributeNamespaceID("entry", defaultNsp);
            if (!NamespaceID.IsValid(entry))
                return null;
            var value = node.GetAttributeLong("value") ?? 0;
            return new ProductStatMeta()
            {
                Category = category,
                Entry = entry,
                Value = value
            };
        }
    }
}
