#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Effects
{
    [EntityBehaviourDefinition(VanillaEffectNames.bigExplosion)]
    public class ExplosionEffect : EffectBehaviour
    {
        public ExplosionEffect(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.SetProperty<float>(PROP_DAMAGE, 100);
            entity.SetProperty<float>(PROP_RADIUS, 60);
            float radius = entity.GetProperty<float>(PROP_RADIUS);
            entity.SetModelProperty("Size", Vector3.one * (radius * 2));
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            float radius = entity.GetProperty<float>(PROP_RADIUS);
            entity.SetModelProperty("Size", Vector3.one * (radius * 2));
        }
        public static readonly VanillaEntityPropertyMeta<float> PROP_DAMAGE = new VanillaEntityPropertyMeta<float>("Damage");
        public static readonly VanillaEntityPropertyMeta<float> PROP_RADIUS = new VanillaEntityPropertyMeta<float>("Radius");
    }
}
