#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace MVZ2.UI
{
    public class OptionsDialogMainPage : MonoBehaviour
    {
        #region 滑动条
        public void SetSliderValue(SliderType type, float value)
        {
            if (sliderDict.TryGetValue(type, out var slider))
            {
                slider.Slider.SetValueWithoutNotify(value);
            }
        }
        public void SetSliderRange(SliderType type, float min, float max, bool integer)
        {
            if (sliderDict.TryGetValue(type, out var slider))
            {
                slider.Slider.minValue = min;
                slider.Slider.maxValue = max;
                slider.Slider.wholeNumbers = integer;
            }
        }
        public void SetSliderText(SliderType type, string text)
        {
            if (sliderDict.TryGetValue(type, out var slider))
            {
                slider.Text.text = text;
            }
        }
        public void SetSliderActive(SliderType type, bool value)
        {
            if (sliderDict.TryGetValue(type, out var slider))
            {
                slider.gameObject.SetActive(value);
                UpdateWidgetAreas();
            }
        }
        #endregion

        #region 按钮
        public void SetButtonText(TextButtonType type, string text)
        {
            if (textButtonDict.TryGetValue(type, out var button))
            {
                button.Text.text = text;
            }
        }
        public void SetButtonActive(ButtonType type, bool value)
        {
            if (buttonDict.TryGetValue(type, out var button))
            {
                button.gameObject.SetActive(value);
                UpdateWidgetAreas();
            }
        }
        #endregion

        #region 切换
        public void SetToggleActive(ToggleType type, bool value)
        {
            if (toggleDict.TryGetValue(type, out var toggle))
            {
                toggle.gameObject.SetActive(value);
                UpdateWidgetAreas();
            }
        }
        public void SetToggleText(ToggleType type, string text)
        {
            if (toggleDict.TryGetValue(type, out var toggle))
            {
                toggle.Text.text = text;
            }
        }
        public void SetToggleOn(ToggleType type, bool value)
        {
            if (toggleDict.TryGetValue(type, out var toggle))
            {
                toggle.Toggle.SetIsOnWithoutNotify(value);
            }
        }
        #endregion

        #region 生命周期
        private void Awake()
{
    // 滑动条
    if (musicSlider != null) sliderDict.Add(SliderType.Music, musicSlider);
    if (soundSlider != null) sliderDict.Add(SliderType.Sound, soundSlider);
    if (fastForwardSlider != null) sliderDict.Add(SliderType.FastForward, fastForwardSlider);

    // 切换开关
    if (swapTriggerToggle != null) toggleDict.Add(ToggleType.SwapTrigger, swapTriggerToggle);
    if (pauseOnFocusLostToggle != null) toggleDict.Add(ToggleType.PauseOnFocusLost, pauseOnFocusLostToggle);

    // 文本按钮
    if (moreOptionsButton != null)
    {
        textButtonDict.Add(TextButtonType.MoreOptions, moreOptionsButton);
        if (moreOptionsButton.Button != null)
            buttonDict.Add(ButtonType.MoreOptions, moreOptionsButton.Button);
    }

    if (diffcultyButton != null)
    {
        textButtonDict.Add(TextButtonType.Difficulty, diffcultyButton);
        if (diffcultyButton.Button != null)
            buttonDict.Add(ButtonType.Difficulty, diffcultyButton.Button);
    }

    if (restartButton != null)
    {
        textButtonDict.Add(TextButtonType.Restart, restartButton);
        if (restartButton.Button != null)
            buttonDict.Add(ButtonType.Restart, restartButton.Button);
    }

    if (leaveLevelButton != null)
    {
        textButtonDict.Add(TextButtonType.LeaveLevel, leaveLevelButton);
        if (leaveLevelButton.Button != null)
            buttonDict.Add(ButtonType.LeaveLevel, leaveLevelButton.Button);
    }

    if (backButton != null)
    {
        textButtonDict.Add(TextButtonType.Back, backButton);
        if (backButton.Button != null)
            buttonDict.Add(ButtonType.Back, backButton.Button);
    }

    // 添加事件监听器时也要检查
    foreach (var pair in sliderDict)
    {
        var type = pair.Key;
        var slider = pair.Value;
        if (slider != null && slider.Slider != null)
        {
            slider.Slider.onValueChanged.AddListener(value => OnSliderValueChanged?.Invoke(type, value));
            if (slider.EndHandler.Exists())
                slider.EndHandler.OnEnd += value => OnSliderEnd?.Invoke(type, slider.Slider.value);
        }
    }
    
    foreach (var pair in buttonDict)
    {
        var type = pair.Key;
        var button = pair.Value;
        if (button != null)
            button.onClick.AddListener(() => OnButtonClick?.Invoke(type));
    }
    
    foreach (var pair in toggleDict)
    {
        var type = pair.Key;
        var toggle = pair.Value;
        if (toggle != null && toggle.Toggle != null)
            toggle.Toggle.onValueChanged.AddListener((v) => OnToggleValueChanged?.Invoke(type, v));
    }
    
    // tooltip handlers 处理
    if (gameObject != null)
    {
        var tooltipHandlers = gameObject.GetComponentsInChildren<TooltipHandler>(true);
        foreach (var handler in tooltipHandlers)
        {
            if (handler != null)
            {
                handler.OnPointerEnter += OnTooltipHandlerPointerEnterCallback;
                handler.OnPointerExit += OnTooltipHandlerPointerExitCallback;
            }
        }
    }
}
        #endregion

        #region 事件回调
        private void OnTooltipHandlerPointerEnterCallback(TooltipHandler handler)
        {
            OnTooltipShow?.Invoke(handler);
        }
        private void OnTooltipHandlerPointerExitCallback(TooltipHandler handler)
        {
            OnTooltipHide?.Invoke(handler);
        }
        #endregion

        private void UpdateWidgetAreas()
        {
            foreach (var line in widgetAreas)
            {
                bool hasActiveChild = HasAnyChildrenElement(line);
                line.gameObject.SetActive(hasActiveChild);
            }
        }
        private bool HasAnyChildrenElement(Transform parent)
        {
            for (int i = 0; i < parent.childCount; i++)
            {
                var child = parent.GetChild(i);
                if (!child || !child.gameObject.activeSelf)
                    continue;
                if (child.GetComponent<IOptionsDialogElement>() != null)
                {
                    return true;
                }
                if (HasAnyChildrenElement(child))
                {
                    return true;
                }
            }
            return false;
        }

        public event Action<SliderType, float>? OnSliderValueChanged;
        public event Action<SliderType, float>? OnSliderEnd;
        public event Action<ButtonType>? OnButtonClick;
        public event Action<ToggleType, bool>? OnToggleValueChanged;
        public event Action<TooltipHandler>? OnTooltipShow;
        public event Action<TooltipHandler>? OnTooltipHide;

        private Dictionary<SliderType, TextSlider> sliderDict = new Dictionary<SliderType, TextSlider>();
        private Dictionary<TextButtonType, TextButton> textButtonDict = new Dictionary<TextButtonType, TextButton>();
        private Dictionary<ButtonType, Button> buttonDict = new Dictionary<ButtonType, Button>();
        private Dictionary<ToggleType, LabeledToggle> toggleDict = new Dictionary<ToggleType, LabeledToggle>();

        [SerializeField]
        private Transform[] widgetAreas = null!;

        [SerializeField]
        private TextSlider musicSlider = null!;
        [SerializeField]
        private TextSlider soundSlider = null!;
        [SerializeField]
        private TextSlider fastForwardSlider = null!;

        [SerializeField]
        private LabeledToggle swapTriggerToggle = null!;
        [SerializeField]
        private LabeledToggle pauseOnFocusLostToggle = null!;

        [SerializeField]
        private TextButton diffcultyButton = null!;
        [SerializeField]
        private TextButton restartButton = null!;

        [SerializeField]
        private TextButton moreOptionsButton = null!;
        [SerializeField]
        private TextButton leaveLevelButton = null!;

        [SerializeField]
        private TextButton backButton = null!;
        public enum SliderType
        {
            Music,
            Sound,
            FastForward,
        }
        public enum TextButtonType
        {
            Difficulty,
            Restart,

            MoreOptions,
            LeaveLevel,

            Back
        }
        public enum ButtonType
        {
            Difficulty,
            Restart,

            MoreOptions,
            LeaveLevel,

            Back
        }
        public enum ToggleType
        {
            SwapTrigger,
            PauseOnFocusLost,
        }
    }
}
