#nullable enable // autogenerated

using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Level
{
    [AutoBuffDefinition(VanillaBuffNames.Level.seijaAutoCollect)]
    public class SeijaAutoCollectBuff : BuffDefinition
    {
        public SeijaAutoCollectBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new BooleanModifier(LogicStageProps.AUTO_COLLECT_ALL, true));
            AddModifier(new BooleanModifier(LogicStageProps.NO_ENERGY, true));
            AddModifier(new BooleanModifier(LogicLevelProps.PAUSE_DISABLED, true));
        }
    }
}
