#nullable enable // autogenerated

using MVZ2.Vanilla;
using MVZ2Logic;
using PVZEngine;

namespace MVZ2.GameContent.Sprites
{
    public static class VanillaSprites
    {
        private static SpriteReference Get(string name)
        {
            var id = new NamespaceID(VanillaMod.spaceName, name);
            return new SpriteReference(id);
        }
        public static readonly SpriteReference starshardDefault = Get("starshards/default");
    }
}
