#nullable enable // autogenerated  

using MVZ2.GameContent.Bosses;
using MVZ2.GameContent.Buffs.Level;
using MVZ2.GameContent.Pickups;
using MVZ2.Vanilla.Bosses;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2.Vanilla.Pickups;
using MVZ2.Vanilla.Properties;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine;
using PVZEngine.Buffs;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Stages
{
    public class Castle15StageBehaviour : BossStageBehaviour
    {
        public Castle15StageBehaviour(StageDefinition stageDef) : base(stageDef)
        {

        }

        public const string PROP_REGION = "castle15_stage_behaviour";
        [LevelPropertyRegistry(PROP_REGION)]
        public static readonly VanillaLevelPropertyMeta<bool> FIELD_SEIJA_SPAWNED =
            new VanillaLevelPropertyMeta<bool>("SeijaSpawned");

        protected override void AfterFinalWaveUpdate(LevelEngine level)
        {
            base.AfterFinalWaveUpdate(level);
            // 与官方 3-11 一致：过渡阶段只召唤凋灵。  
            // 此时场上没有其它 Boss，WitherTransitionBuff 的状态机自洽，  
            // 凋灵出现后会切到 STATE_BOSS_FIGHT，不会重复召唤。  
            StartBossTransitionUpdate<WitherTransitionBuff>(level);
        }

        protected override void BossFightWaveUpdate(LevelEngine level)
        {
            base.BossFightWaveUpdate(level);

            // 进入 Boss 战后再生成 Seija，让她从右侧前空翻跳入场地（只生成一次）。  
            // 放到此处是为了避免 Seija 作为敌对 Boss 干扰 WitherTransitionBuff 的状态判定，  
            // 否则会导致凋灵被无限召唤。  
            if (!level.GetProperty<bool>(FIELD_SEIJA_SPAWNED))
            {
                var x = LevelPositions.ENEMY_RIGHT_BORDER;
                var z = level.GetEntityLaneZ(level.GetMaxLaneCount() / 2);
                var y = level.GetGroundY(x, z);
                level.Spawn(VanillaBossID.seija, new Vector3(x, y, z), null)?.Let(seija =>
                {
                    Seija.StartState(seija, VanillaBossStates.SEIJA_FRONTFLIP);
                    seija.InflictRegenerationBuff(1000f, 300, new EntitySourceReference(seija));
                });
                level.SetProperty(FIELD_SEIJA_SPAWNED, true);
            }

            WitherFightUpdate(level);
        }

        private void WitherFightUpdate(LevelEngine level)
        {
            // 检测两个 Boss 是否存活  
            var witherExists = level.EntityExists(e => e.IsEntityOf(VanillaBossID.wither) && e.IsHostileEntity() && !e.IsDead);
            var seijaExists = level.EntityExists(e => e.IsEntityOf(VanillaBossID.seija) && e.IsHostileEntity() && !e.IsDead);

            // 只有两个 Boss 都不存在时才进入胜利阶段  
            if (!witherExists && !seijaExists)
            {
                level.WaveState = VanillaLevelStates.STATE_AFTER_BOSS;
                level.StopMusic();

                Vector3 position;
                var x = level.GetLawnCenterX();
                var z = level.GetLawnCenterZ();
                var y = level.GetGroundY(x, z);
                position = new Vector3(x, y, z);

                level.Produce(VanillaPickupID.clearPickup, position, null);
            }
            else
            {
                RunBossWave(level);
            }
        }

        protected override void AfterBossWaveUpdate(LevelEngine level)
        {
            base.AfterBossWaveUpdate(level);
            ClearEnemies(level);

            if (!level.IsRerun)
            {
                if (!level.IsCleared && !level.EntityExists(e => e.Type == EntityTypes.BOSS && e.IsHostileEntity()))
                {
                    if (!level.HasBuff<WitherClearedBuff>())
                    {
                        level.AddBuff<WitherClearedBuff>();
                    }
                }
            }
        }
    }
}
