#nullable enable // autogenerated

using MVZ2.GameContent.Bosses;
using MVZ2.GameContent.Buffs.Enemies;
using MVZ2.GameContent.Buffs.Level;
using MVZ2.GameContent.Pickups;
using MVZ2.Vanilla.Entities;
using MVZ2.Vanilla.Level;
using MVZ2Logic.Level;
using PVZEngine.Buffs;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.GameContent.Stages
{
    public class RedDragonStageBehaviour : BossStageBehaviour
    {
        public RedDragonStageBehaviour(StageDefinition stageDef) : base(stageDef)
        {
        }
        public override void PostWave(LevelEngine level, int wave)
        {
            base.PostWave(level, wave);
            if (wave <= 10)
                return;
            if (!level.HasBuff<RedDragonStageBuff>())
            {
                level.AddBuff<RedDragonStageBuff>();
            }
        }
        protected override void AfterFinalWaveUpdate(LevelEngine level)
        {
            base.AfterFinalWaveUpdate(level);
            TransitionUpdate(level);
        }
        private void TransitionUpdate(LevelEngine level)
        {
            if (level.EntityExists(e => e.Type == EntityTypes.BOSS && e.IsHostileEntity() && !e.IsDead && e.State == RedDragon.STATE_IDLE))
            {
                // 红龙出现
                level.WaveState = VanillaLevelStates.STATE_BOSS_FIGHT;
                return;
            }
            if (!level.HasBuff<RedDragonTransitionBuff>())
            {
                level.AddBuff<RedDragonTransitionBuff>();
            }
        }
        protected override void BossFightWaveUpdate(LevelEngine level)
        {
            base.BossFightWaveUpdate(level);
            RedDragonUpdate(level);
        }
        private void RedDragonUpdate(LevelEngine level)
        {
            // 红龙战斗
            // 如果有Boss存活，不停生成怪物。
            // 如果不存在Boss，或者所有Boss死亡，进入BOSS后阶段。
            if (level.EntityExists(e => e.Type == EntityTypes.BOSS && e.IsHostileEntity() && !e.IsDead))
            {
                RunBossWave(level);
            }
            else
            {
                level.WaveState = VanillaLevelStates.STATE_AFTER_BOSS;
                level.StopMusic();
                if (!level.IsRerun && level.IsAdventure())
                {
                    // 隐藏UI，关闭输入
                    level.ResetHeldItem();
                    level.SetUIAndInputDisabled(true);
                }
                else
                {
                    // 生成通关掉落物。
                    var giant = level.FindFirstEntity(VanillaBossID.redDragon);
                    Vector3 position;
                    if (giant != null)
                    {
                        position = giant.Position;
                    }
                    else
                    {
                        var x = level.GetLawnCenterX();
                        var z = level.GetLawnCenterZ();
                        var y = level.GetGroundY(x, z);
                        position = new Vector3(x, y, z);
                    }
                    ClearPickup.Produce(level, position);
                }
            }
        }
        protected override void AfterBossWaveUpdate(LevelEngine level)
        {
            base.AfterBossWaveUpdate(level);
            ClearEnemies(level);
            if (!level.IsRerun)
            {
                if (!level.IsCleared)
                {
                    if (!level.EntityExists(e => e.Type == EntityTypes.BOSS && e.IsHostileEntity() && !e.IsDead))
                    {
                        if (!level.HasBuff<RedDragonClearedBuff>())
                        {
                            level.AddBuff<RedDragonClearedBuff>();
                        }
                    }
                }
            }
        }
    }
}
