#nullable enable // autogenerated  
  
using MVZ2.GameContent.Buffs.Enemies;  
using MVZ2.GameContent.Buffs.Projectiles;  
using MVZ2.GameContent.Detections;  
using MVZ2.GameContent.Difficulties;  
using MVZ2.Vanilla.Audios;  
using MVZ2.Vanilla.Detections;  
using MVZ2.Vanilla.Enemies;  
using MVZ2.Vanilla.Entities;  
using MVZ2.Vanilla.Properties;  
using PVZEngine.Buffs;  
using PVZEngine.Damages;  
using PVZEngine.Entities;  
using PVZEngine.Level;
using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Level;
using UnityEngine;
using Tools;  
  
namespace MVZ2.GameContent.Enemies  
{  
    [EntityBehaviourDefinition(VanillaEnemyNames.AngryGhast)]  
    public class AngryGhast : AIEntityBehaviour  
    {  
        public AngryGhast(string nsp, string name) : base(nsp, name)  
        {  
            detector = new DispenserDetector()  
            {  
                ignoreHighEnemy = true  
            };  
        }  
        public override void Init(Entity entity)  
        {  
            base.Init(entity);  
            SetStateTimer(entity, new FrameTimer(SHOOT_COOLDOWN));  
            SetBurstTimer(entity, new FrameTimer(BURST_INTERVAL));  
            SetBurstCount(entity, 0);  
            SetShotIndex(entity, 0);  
            var buff = entity.AddBuff<FlyBuff>();  
            buff.SetProperty(FlyBuff.PROP_TARGET_HEIGHT, 80f);  
        }
        protected override void UpdateAI(Entity enemy)
        {
            base.UpdateAI(enemy);

            // 处理三连发的后续射击：等待间隔到期后，重新进入攻击准备阶段  
            int burstCount = GetBurstCount(enemy);
            if (burstCount > 0 && enemy.State == STATE_WALK)
            {
                var burstTimer = GetBurstTimer(enemy);
                if (burstTimer != null && burstTimer.RunToExpired(enemy.GetAttackSpeed()))
                {
                    var target = FindTarget(enemy);
                    if (target != null && target.Exists())
                    {
                        // 像正常攻击一样：设置 Target，让引擎切换到 RANGED_ATTACK 状态  
                        enemy.Target = target;
                        var shootTimer = GetStateTimer(enemy);
                        shootTimer?.ResetTime(SHOOT_DURATION);
                        enemy.PlayCrySound(VanillaSoundID.ghast_affectionate_scream);
                        // 不在这里 Fire，等 STATE_RANGED_ATTACK 的计时器到期后再 Fire  
                    }
                    else
                    {
                        // 没有目标，跳过这发，继续下一发  
                        SetBurstCount(enemy, burstCount - 1);
                        burstTimer.ResetTime(BURST_INTERVAL);
                    }
                }
                return; // 连射期间不执行正常冷却逻辑  
            }

            if (CanShoot(enemy))
            {
                var shootTimer = GetStateTimer(enemy);
                if (shootTimer != null)
                {
                    shootTimer.Run(enemy.GetAttackSpeed());
                    switch (enemy.State)
                    {
                        case STATE_WALK:
                            if (shootTimer.Expired)
                            {
                                var target = FindTarget(enemy);
                                if (target != null && target.Exists())
                                {
                                    enemy.Target = target;
                                    shootTimer.ResetTime(SHOOT_DURATION);
                                    // 第三次攻击（ShotIndex==2）的第一发也用特殊音效  
                                    if (GetShotIndex(enemy) == 2)
                                        enemy.PlayCrySound(VanillaSoundID.ghast_affectionate_scream);
                                    else
                                        enemy.PlayCrySound(VanillaSoundID.ghastFire);
                                }
                                else
                                {
                                    shootTimer.Reset();
                                }
                            }
                            break;
                        case STATE_RANGED_ATTACK:
                            if (shootTimer.Expired)
                            {
                                var target = FindTarget(enemy);
                                if (target != null && target.Exists())
                                {
                                    Fire(enemy, target);
                                }
                                enemy.Target = null;

                                int burstRemaining = GetBurstCount(enemy);
                                if (burstRemaining > 0)
                                {
                                    // 正在连射中：递减 BurstCount，不动 ShotIndex  
                                    SetBurstCount(enemy, burstRemaining - 1);
                                    if (burstRemaining - 1 > 0)
                                    {
                                        var bt = GetBurstTimer(enemy);
                                        bt?.ResetTime(BURST_INTERVAL);
                                    }
                                    shootTimer.ResetTime(SHOOT_COOLDOWN);
                                }
                                else
                                {
                                    // 不在连射中：正常处理 ShotIndex  
                                    int shotIndex = GetShotIndex(enemy);
                                    if (shotIndex == 2)
                                    {
                                        // 第三次攻击的第1发刚发射，启动连射  
                                        SetBurstCount(enemy, BURST_TOTAL - 1);
                                        var bt = GetBurstTimer(enemy);
                                        bt?.ResetTime(BURST_INTERVAL);
                                        SetShotIndex(enemy, 0); // 重置循环  
                                    }
                                    else
                                    {
                                        SetShotIndex(enemy, shotIndex + 1);
                                    }
                                    shootTimer.ResetTime(SHOOT_COOLDOWN);
                                }
                            }
                            break;
                    }
                }
            }
        }
        public override void PostDeath(Entity entity, DeathInfo info)
        {
            base.PostDeath(entity, info);
            if (info.HasEffect(VanillaDamageEffects.NO_DEATH_TRIGGER))
                return;
            Explode(entity, entity.GetDamage() * 3, entity.GetFaction());
            entity.Remove();
        }
        public static void Explode(Entity entity, float damage, int faction)
        {
            var effects = new DamageEffectList(VanillaDamageEffects.EXPLOSION, VanillaDamageEffects.DAMAGE_BODY_AFTER_ARMOR_BROKEN, VanillaDamageEffects.MUTE);
            Explode(entity, damage, effects, faction);
        }
        public static void Explode(Entity entity, float damage, DamageEffectList effects, int faction)
        {
            var scale = entity.GetFinalScale();
            var scaleX = Mathf.Abs(scale.x);
            var range = 70 * scaleX;
            entity.Explode(entity.GetCenter(), range, faction, damage, effects);

            Explosion.Spawn(entity, entity.GetCenter(), range);

            entity.PlaySound(VanillaSoundID.explosion, scaleX == 0 ? 1000 : 1 / (scaleX));
        }

        // --- State Timer ---  
        public static FrameTimer? GetStateTimer(Entity enemy)  
            => enemy.GetBehaviourField<FrameTimer>(PROP_STATE_TIMER);  
        public static void SetStateTimer(Entity enemy, FrameTimer value)  
            => enemy.SetBehaviourField(PROP_STATE_TIMER, value);  
  
        // --- Shot Index (0, 1, 2 循环) ---  
        public static int GetShotIndex(Entity enemy)  
            => enemy.GetBehaviourField<int>(PROP_SHOT_INDEX);  
        public static void SetShotIndex(Entity enemy, int value)  
            => enemy.SetBehaviourField(PROP_SHOT_INDEX, value);  
  
        // --- Burst Count & Timer ---  
        public static int GetBurstCount(Entity enemy)  
            => enemy.GetBehaviourField<int>(PROP_BURST_COUNT);  
        public static void SetBurstCount(Entity enemy, int value)  
            => enemy.SetBehaviourField(PROP_BURST_COUNT, value);  
        public static FrameTimer? GetBurstTimer(Entity enemy)  
            => enemy.GetBehaviourField<FrameTimer>(PROP_BURST_TIMER);  
        public static void SetBurstTimer(Entity enemy, FrameTimer value)  
            => enemy.SetBehaviourField(PROP_BURST_TIMER, value);  
  
        protected virtual bool CanShoot(Entity enemy)  
        {  
            return enemy.Position.x <= enemy.Level.GetEntityColumnX(enemy.Level.GetMaxColumnCount() - 1);  
        }  
        protected virtual Entity? FindTarget(Entity entity)  
        {  
            return detector.DetectEntityWithTheLeast(entity, e => (e.GetCenter() - entity.Position).sqrMagnitude);  
        }  
        protected virtual bool ValidateTarget(Entity entity, Entity target)  
        {  
            return detector.ValidateTarget(entity, target);  
        }  
        private void Fire(Entity self, Entity target)  
        {  
            var scale = self.GetScale();  
            var param = self.GetShootParams();  
            var shootPoint = self.GetShootPoint();  
            var velocity = self.GetShotVelocity();  
            var speed = velocity.magnitude;  
            var direciton = (target.GetCenter() - shootPoint).normalized;  
            param.velocity = speed * direciton;  
            var damageMultiplier = self.Level.GetGhastDamageMultiplier();  
            param.damage = self.GetDamage() * damageMultiplier;  
  
            var bullet = self.ShootProjectile(param)?.Let(e =>  
            {  
                var buff = e.AddBuff<GhastFireChargeBuff>();  
                GhastFireChargeBuff.SetScaleMultiplier(buff, scale);  
                GhastFireChargeBuff.SetRangeMultiplier(buff, scale.x);  
                GhastFireChargeBuff.SetDamageMultiplier(buff, scale.x);  
            });  
            self.PlaySound(VanillaSoundID.fireCharge, scale.x);  
        }  
  
        private Detector detector;  
  
        // 属性定义  
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_STATE_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("StateTimer");  
        public static readonly VanillaEntityPropertyMeta<int> PROP_SHOT_INDEX = new VanillaEntityPropertyMeta<int>("ShotIndex");  
        public static readonly VanillaEntityPropertyMeta<int> PROP_BURST_COUNT = new VanillaEntityPropertyMeta<int>("BurstCount");  
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_BURST_TIMER = new VanillaEntityPropertyMeta<FrameTimer>("BurstTimer");  
  
        // 常量  
        public const int SHOOT_COOLDOWN = 135;  
        public const int SHOOT_DURATION = 15;  
        public const int BURST_TOTAL = 3;        // 三连发总共3发  
        public const int BURST_INTERVAL = 20;    // 每发间隔20帧（约0.67秒）  
        public const int STATE_WALK = VanillaEnemyStates.WALK;  
        public const int STATE_RANGED_ATTACK = VanillaEnemyStates.RANGED_ATTACK;  
    }  
}