#nullable enable // autogenerated

using PVZEngine.Definitions;

namespace MVZ2.GameContent.Effects
{
    [AutoEntityBehaviourDefinition(VanillaEffectNames.RadiationLight)]
    public class RadiationLight : EffectBehaviour
    {

        #region 公有方法
        public RadiationLight(string nsp, string name) : base(nsp, name)
        {
        }
        #endregion
    }
}
