#nullable enable // autogenerated

using MVZ2.GameContent.Damages;
using MVZ2.GameContent.Effects;
using MVZ2.Vanilla.Audios;
using MVZ2Logic.Blueprints;
using MVZ2Logic.Definitions;
using MVZ2Logic.Entities;
using MVZ2Logic.Level;
using PVZEngine.Damages;
using PVZEngine.Entities;
using PVZEngine.Level;
using PVZEngine.SeedPacks;
using UnityEngine;

namespace MVZ2.GameContent.Seeds
{
    [AutoSeedOptionDefinition(VanillaBlueprintNames.heavyWeaponNuke)]
    public class HeavyWeaponNuke : SeedOptionDefinition
    {
        public HeavyWeaponNuke(string nsp, string name) : base(nsp, name)
        {
        }
        public override void Use(SeedPack seedPack)
        {
            base.Use(seedPack);
            Use(seedPack.Level);
        }
        public override void Use(LevelEngine level, SeedDefinition seedDef)
        {
            base.Use(level, seedDef);
            Use(level, seedDef);
        }
        private void Use(LevelEngine level)
        {
            var deathEffects = new DamageEffectList(VanillaDamageEffects.INSTA_KILL, VanillaDamageEffects.MUTE, VanillaDamageEffects.NO_DEATH_EFFECTS, VanillaDamageEffects.REMOVE_ON_DEATH);

            foreach (var ent in level.FindEntities(e => e.IsHostileEntity()))
            {
                ent.Die(deathEffects, (Entity?)null);
            }

            var smokeSpawnParam = new SpawnParams();
            smokeSpawnParam.SetProperty(EngineEntityProps.TINT, new Color(0, 0.5f, 0, 1));
            var position = level.GetLawnCenter();
            level.Spawn(VanillaEffectID.nukeSmoke, position, null, smokeSpawnParam);
            level.Spawn(VanillaEffectID.nukeFlash, level.GetLawnCenter(), null, smokeSpawnParam);
            level.PlaySound(VanillaSoundID.nukeblast);
            level.ShakeScreen(10, 0, 60);
        }
    }
}
