#nullable enable // autogenerated

using MVZ2.GameContent.Contraptions;
using MVZ2.GameContent.Enemies;
using MVZ2.GameContent.Seeds;
using MVZ2.GameContent.Stages;
using MVZ2Logic.Blueprints;
using MVZ2Logic.Definitions;
using MVZ2Logic.IZombie;
using PVZEngine;
using Tools;

namespace MVZ2.GameContent.IZombie
{
    [AutoIZombieLayoutDefinition(VanillaIZombieLayoutNames.puzzleAmongUs)]
    public class PuzzleAmongUsLayout : IZombieLayoutDefinition
    {
        public PuzzleAmongUsLayout(string nsp, string name) : base(nsp, name, 5)
        {
            Blueprints = new NamespaceID[]
            {
                LogicBlueprintID.FromEntity(VanillaEnemyID.imp),
                LogicBlueprintID.FromEntity(VanillaEnemyID.leatherCappedZombie),
                VanillaBlueprintID.ufoRed,
                LogicBlueprintID.FromEntity(VanillaEnemyID.ironHelmettedZombie)
            };
        }
        public override void Fill(IIZombieMap map, RandomGenerator rng)
        {
            FillColumn(map, 4, VanillaContraptionID.splitenser);
            FillColumn(map, 0, VanillaContraptionID.gravityPad);

            Insert(map, 0, 0, VanillaContraptionID.furnace);
            Insert(map, 0, 1, VanillaContraptionID.soulFurnace);
            Insert(map, 0, 2, VanillaContraptionID.repeatenser);
            Insert(map, 0, 3, VanillaContraptionID.furnace);
            Insert(map, 0, 4, VanillaContraptionID.furnace);

            Insert(map, 1, 4, VanillaContraptionID.noteBlock);
            Insert(map, 2, 4, VanillaContraptionID.gunpowderBarrel);
            Insert(map, 3, 4, VanillaContraptionID.furnace);
            Insert(map, 1, 3, VanillaContraptionID.repeatenser);
            Insert(map, 2, 3, VanillaContraptionID.furnace);
            Insert(map, 3, 3, VanillaContraptionID.triplenser);

            Insert(map, 1, 1, VanillaContraptionID.gunpowderBarrel);
            Insert(map, 1, 1, VanillaContraptionID.stoneShield);
            Insert(map, 2, 1, VanillaContraptionID.furnace);
            Insert(map, 3, 1, VanillaContraptionID.repeatenser);

            RandomFill(map, VanillaContraptionID.repeatenser, 1, rng);
            RandomFill(map, VanillaContraptionID.triplenser, 3, rng);
            // RandomFill(map, VanillaContraptionID.splitenser, 2, rng);
            RandomFill(map, VanillaContraptionID.furnace, 2, rng);
        }
    }
}
