#nullable enable // autogenerated

using PVZEngine.Buffs;
using PVZEngine.Level;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Buffs.Level
{
    [BuffDefinition(VanillaBuffNames.Level.debugNoRecharge)]
    public class DebugNoRechargeBuff : BuffDefinition
    {
        public DebugNoRechargeBuff(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(EngineLevelProps.RECHARGE_SPEED, NumberOperator.Set, 99999999));
        }
    }
}
