#nullable enable // autogenerated  

using MVZ2.GameContent.Projectiles;  
using MVZ2.Vanilla.Audios;  
using MVZ2.Vanilla.Contraptions;  
using MVZ2.Vanilla.Entities;  
using MVZ2.Vanilla.Properties;  
using MVZ2Logic.Level;  
using PVZEngine;  
using PVZEngine.Entities;  
using PVZEngine.Level;  
using Tools;  
using UnityEngine;  
  
namespace MVZ2.GameContent.Contraptions  
{  
    [EntityBehaviourDefinition(VanillaContraptionNames.DispenShield)]  
    public class DispenShield : DispenserFamily  
    {  
        public DispenShield(string nsp, string name) : base(nsp, name)  
        {  
        }  
  
        public override void Init(Entity entity)  
        {  
            base.Init(entity);  
            InitShootTimer(entity);  
            // 大招计时器：120帧，每6帧射一发 = 20发  
            SetEvocationTimer(entity, new FrameTimer(120));  
        }  
  
        protected override void UpdateAI(Entity entity)  
        {  
            base.UpdateAI(entity);  
            if (!entity.IsEvoked())  
            {  
                ShootTick(entity);  
                return;  
            }  
            // 大招状态  
            EvokedUpdate(entity);  
        }  
  
        public override Entity? Shoot(Entity entity)  
        {  
            var mainEntity = entity.GetFirstProtectingTarget();  
  
            if (mainEntity != null)  
            {  
                var mainProjectileID = mainEntity.GetProjectileID();  
                if (mainProjectileID != null)  
                {  
                    entity.TriggerAnimation("Shoot");  
                    var param = entity.GetShootParams();  
                    param.projectileID = mainProjectileID;  
                    param.damage = entity.GetDamage();  //发射器护罩本身的伤害
  
                    // 上方器械子弹为arrow时，发射2发  
                    if (mainProjectileID == VanillaProjectileID.arrow)  
                    {  
                        var proj1 = entity.ShootProjectile(param);  
                        if (proj1 != null)  
                            proj1.Timeout = Mathf.CeilToInt(entity.GetRange() / entity.GetShotVelocity().magnitude);  
  
                        // 第二发，稍微偏移x轴避免完全重叠  
                        var param2 = entity.GetShootParams();  
                        param2.projectileID = mainProjectileID;  
                        param2.damage = entity.GetDamage();  
                        param2.velocity = new Vector3(param2.velocity.x + 1f, param2.velocity.y, param2.velocity.z);  
                        var proj2 = entity.ShootProjectile(param2);  
                        if (proj2 != null)  
                            proj2.Timeout = Mathf.CeilToInt(entity.GetRange() / entity.GetShotVelocity().magnitude);  
  
                        return proj1;  
                    }  
  
                    // 判定上方为特定器械时发射特定子弹  
                    // 例如：上方是发射器(dispenser)时，发射紫色箭矢  
                    // if (mainEntity.GetDefinitionID() == VanillaContraptionID.dispenser)  
                    // {  
                    //     param.projectileID = VanillaProjectileID.purpleArrow;  
                    //     param.damage = mainEntity.GetDamage() * 2;  
                    // }  
                    //  
                    // 例如：上方是灵魂熔炉(soulFurnace)时，发射火球  
                    // if (mainEntity.GetDefinitionID() == VanillaContraptionID.soulFurnace)  
                    // {  
                    //     param.projectileID = VanillaProjectileID.soulfireBall;  
                    //     param.damage = mainEntity.GetDamage() * 1.5f;  
                    // }  
  
                    var projectile = entity.ShootProjectile(param);  
                    if (projectile != null)  
                        projectile.Timeout = Mathf.CeilToInt(entity.GetRange() / entity.GetShotVelocity().magnitude);  
                    return projectile;  
                }  
            }  
  
            // 没有上方器械，使用默认箭矢  
            var defaultProjectile = base.Shoot(entity);  
            if (defaultProjectile != null)  
                defaultProjectile.Timeout = Mathf.CeilToInt(entity.GetRange() / entity.GetShotVelocity().magnitude);  
            return defaultProjectile;  
        }  
  
        //大招：上方有器械时连射20发复制子弹  
        protected override void OnEvoke(Entity entity)  
        {  
            base.OnEvoke(entity);  
            var mainEntity = entity.GetFirstProtectingTarget();  
  
            if (mainEntity != null && mainEntity.GetProjectileID() != null)  
            {  
                // 上方有器械，进入连射模式  
                var evocationTimer = GetEvocationTimer(entity);  
                evocationTimer?.Reset();  
                entity.SetEvoked(true);  
            }  
            else  
            {  
                // 没有上方器械，使用原来的大雪球大招  
                var velocity = Vector3.right * 3;  
                if (entity.IsFacingLeft())  
                {  
                    velocity.x *= -1;  
                }  
                entity.ShootProjectile(VanillaProjectileID.largeSnowball, velocity);  
                entity.PlaySound(VanillaSoundID.odd);  
            }  
        }  
  
        private void EvokedUpdate(Entity entity)  
        {  
            var evocationTimer = GetEvocationTimer(entity);  
            if (evocationTimer == null)  
                return;  
            evocationTimer.Run();  
  
            // 每6帧射一发，120帧总共20发  
            if (evocationTimer.PassedInterval(6))  
            {  
                var projectile = Shoot(entity);  
                if (projectile != null)  
                    projectile.Velocity *= 2; // 大招子弹速度翻倍  
            }  
  
            if (evocationTimer.Expired)  
            {  
                entity.SetEvoked(false);  
                var shootTimer = GetShootTimer(entity);  
                shootTimer?.Reset();  
            }  
        }  
  
        // 存储大招计时器的字段  
        public static FrameTimer? GetEvocationTimer(Entity entity) =>  
            entity.GetBehaviourField<FrameTimer>(ID, PROP_EVOCATION_TIMER);  
  
        public static void SetEvocationTimer(Entity entity, FrameTimer timer) =>  
            entity.SetBehaviourField(ID, PROP_EVOCATION_TIMER, timer);  
  
        private static readonly NamespaceID ID = VanillaContraptionID.DispenShield;  
        public static readonly VanillaEntityPropertyMeta<FrameTimer> PROP_EVOCATION_TIMER =  
            new VanillaEntityPropertyMeta<FrameTimer>("EvocationTimer");  
    }  
}