#nullable enable // autogenerated

using MVZ2.Vanilla.Entities;
using MVZ2Logic.Entities;
using MVZ2.Vanilla.Properties;
using PVZEngine.Definitions;
using PVZEngine.Entities;
using PVZEngine.Modifiers;

namespace MVZ2.GameContent.Entities
{
    [AutoBuffDefinition(VanillaEntityBehaviourNames.entityPhysics)]
    public class EntityPhysicsBehaviour : EntityBehaviourDefinition
    {
        public EntityPhysicsBehaviour(string nsp, string name) : base(nsp, name)
        {
            AddModifier(new FloatModifier(EngineEntityProps.FRICTION, NumberOperator.Multiply, PROP_FRICTION));
        }
        public override void Init(Entity entity)
        {
            base.Init(entity);
            entity.SetProperty(PROP_FRICTION, 1f);
            UpdateMultipliers(entity);
        }
        public override void Update(Entity entity)
        {
            base.Update(entity);
            UpdateMultipliers(entity);
        }
        private void UpdateMultipliers(Entity entity)
        {
            float friction = 1;
            if (!entity.IsOnGround && !entity.KeepGroundFriction())
            {
                friction = 0.1f;
            }
            entity.SetProperty(PROP_FRICTION, friction);
        }
        public static readonly VanillaEntityPropertyMeta<float> PROP_FRICTION = new VanillaEntityPropertyMeta<float>("friction");
    }
}
