#nullable enable // autogenerated

using PVZEngine.Entities;
using PVZEngine.Level;

namespace MVZ2.GameContent.Enemies
{
    [EntityBehaviourDefinition(VanillaEnemyNames.PirateZombie)]
    public class PirateZombie : Zombie
    {
        public PirateZombie(string nsp, string name) : base(nsp, name)
        {
        }
    }
}
